CREATE TABLE B_B24CONNECTOR_BUTTONS
(
  ID INT NOT NULL,
  APP_ID INT NOT NULL,
  ADD_DATE DATETIME NOT NULL,
  ADD_BY INT NOT NULL,
  NAME VARCHAR(255) NULL,
  SCRIPT TEXT NULL
)
GO
ALTER TABLE B_B24CONNECTOR_BUTTONS ADD CONSTRAINT PK_B_B24CONNECTOR_BUTTONS PRIMARY KEY (ID)
GO