DROP TABLE B_SALE_AUXILIARY
GO
DROP TABLE B_SALE_LANG
GO
DROP TABLE B_SALE_FUSER
GO
DROP TABLE B_SALE_BASKET
GO
DROP TABLE B_SALE_BASKET_PROPS
GO
DROP TABLE B_SALE_ORDER
GO
DROP TABLE B_SALE_PERSON_TYPE
GO
DROP TABLE B_SALE_ORDER_PROPS_GROUP
GO
DROP TABLE B_SALE_ORDER_PROPS
GO
DROP TABLE B_SALE_ORDER_PROPS_VALUE
GO
DROP TABLE B_SALE_ORDER_PROPS_VARIANT
GO
DROP TABLE B_SALE_ORDER_PROPS_RELATION
GO
DROP TABLE B_SALE_PAY_SYSTEM_ACTION
GO
DROP TABLE B_SALE_DELIVERY
GO
DROP TABLE B_SALE_LOCATION_COUNTRY
GO
DROP TABLE B_SALE_LOCATION_COUNTRY_LANG
GO
DROP TABLE B_SALE_LOCATION_CITY
GO
DROP TABLE B_SALE_LOCATION_CITY_LANG
GO
DROP TABLE B_SALE_LOCATION_REGION
GO
DROP TABLE B_SALE_LOCATION_REGION_LANG
GO
DROP TABLE B_SALE_LOCATION_ZIP
GO
DROP TABLE B_SALE_LOCATION
GO
DROP TABLE B_SALE_LOC_NAME
GO
DROP TABLE B_SALE_LOC_EXT_SRV
GO
DROP TABLE B_SALE_LOC_EXT
GO
DROP TABLE B_SALE_LOC_TYPE
GO
DROP TABLE B_SALE_LOC_TYPE_NAME
GO
DROP TABLE B_SALE_LOC_2SITE
GO
DROP TABLE B_SALE_LOC_DEF2SITE
GO
DROP TABLE B_SALE_LOCATION_GROUP
GO
DROP TABLE B_SALE_LOCATION_GROUP_LANG
GO
DROP TABLE B_SALE_LOCATION2LOCATION_GROUP
GO
DROP TABLE B_SALE_DELIVERY2LOCATION
GO
DROP TABLE B_SALE_DISCOUNT
GO
DROP TABLE B_SALE_DISCOUNT_COUPON
GO
DROP TABLE B_SALE_DISCOUNT_GROUP
GO
DROP TABLE B_SALE_DISCOUNT_MODULE
GO
DROP TABLE B_SALE_DISCOUNT_ENTITIES
GO
DROP TABLE B_SALE_ORDER_DISCOUNT
GO
DROP TABLE B_SALE_ORDER_COUPONS
GO
DROP TABLE B_SALE_ORDER_MODULES
GO
DROP TABLE B_SALE_ORDER_RULES
GO
DROP TABLE B_SALE_ORDER_RULES_DESCR
GO
DROP TABLE B_SALE_ORDER_DISCOUNT_DATA
GO
DROP TABLE B_SALE_ORDER_ROUND
GO
DROP TABLE B_SALE_USER_PROPS
GO
DROP TABLE B_SALE_D_IX_ELEMENT
GO
DROP TABLE B_SALE_D_IX_SECTION
GO
DROP TABLE B_SALE_USER_PROPS_VALUE
GO
DROP TABLE B_SALE_STATUS
GO
DROP TABLE B_SALE_STATUS_LANG
GO
DROP TABLE B_SALE_STATUS_GROUP_TASK
GO
DROP TABLE B_SALE_TAX
GO
DROP TABLE B_SALE_ORDER_TAX
GO
DROP TABLE B_SALE_TAX_RATE
GO
DROP TABLE B_SALE_TAX2LOCATION
GO
DROP TABLE B_SALE_TAX_EXEMPT2GROUP
GO
DROP TABLE B_SALE_ORDER_FLAGS2GROUP
GO
DROP TABLE B_SALE_SITE2GROUP
GO
DROP TABLE B_SALE_USER_ACCOUNT
GO
DROP TABLE B_SALE_RECURRING
GO
DROP TABLE B_SALE_USER_CARDS
GO
DROP TABLE B_SALE_USER_TRANSACT
GO
DROP TABLE B_SALE_AFFILIATE_PLAN
GO
DROP TABLE B_SALE_AFFILIATE
GO
DROP TABLE B_SALE_AFFILIATE_PLAN_SECTION
GO
DROP TABLE B_SALE_AFFILIATE_TIER
GO
DROP TABLE B_SALE_AFFILIATE_TRANSACT
GO
DROP TABLE B_SALE_EXPORT
GO
DROP TABLE B_SALE_DELIVERY_HANDLER
GO
DROP TABLE B_SALE_PRODUCT2PRODUCT
GO
DROP TABLE B_SALE_PERSON_TYPE_SITE
GO
DROP TABLE B_SALE_VIEWED_PRODUCT
GO
DROP TABLE B_SALE_ORDER_HISTORY
GO
DROP TABLE B_SALE_DELIVERY2PAYSYSTEM
GO
DROP TABLE B_SALE_STORE_BARCODE
GO
DROP TABLE B_SALE_ORDER_CHANGE
GO
DROP TABLE B_SALE_ORDER_DELIVERY
GO
DROP TABLE B_SALE_ORDER_DELIVERY_REQ
GO
DROP TABLE B_SALE_ORDER_PROCESSING
GO
DROP TABLE B_SALE_TP
GO
DROP TABLE B_SALE_BIZVAL
GO
DROP TABLE B_SALE_BIZVAL_PERSONDOMAIN
GO
DROP TABLE B_SALE_BIZVAL_CODE_1C
GO
DROP TABLE B_SALE_DELIVERY_SRV
GO
DROP TABLE B_SALE_SERVICE_RSTR
GO
DROP TABLE B_SALE_DELIVERY_ES
GO
DROP TABLE B_SALE_ORDER_DELIVERY_ES
GO
DROP TABLE B_SALE_ORDER_DLV_BASKET
GO
DROP TABLE B_SALE_TP_MAP
GO
DROP TABLE B_SALE_TP_MAP_ENTITY
GO
DROP TABLE B_SALE_TP_EBAY_CAT
GO
DROP TABLE B_SALE_TP_EBAY_CAT_VAR
GO
DROP TABLE B_SALE_TP_EBAY_FQ
GO
DROP TABLE B_SALE_TP_EBAY_FR
GO
DROP TABLE B_SALE_TP_ORDER
GO
DROP TABLE B_SALE_GIFT_RELATED_DATA
GO
DROP TABLE B_SALE_ORDER_PAYMENT_ES
GO
DROP TABLE B_SALE_PAYMENT_ES
GO
DROP TABLE B_SALE_PAY_SYSTEM_RSTR
GO
DROP TABLE B_SALE_PAY_SYSTEM_ERR_LOG
GO
DROP TABLE B_SALE_HDALN
GO
DROP TABLE B_SALE_COMPANY
GO
DROP TABLE B_SALE_COMPANY2LOCATION
GO
DROP TABLE B_SALE_COMPANY2SERVICE
GO
DROP TABLE B_SALE_YANDEX_SETTINGS
GO
DROP TABLE B_SALE_ENTITY_MARKER
GO
DROP TABLE B_SALE_TP_VK_PROFILE
GO
DROP TABLE B_SALE_TP_VK_LOG
GO
DROP TABLE B_SALE_ORDER_ARCHIVE
GO
DROP TABLE B_SALE_BASKET_ARCHIVE
GO
DROP TABLE B_SALE_COMPANY_GROUP
GO
DROP TABLE B_SALE_COMPANY_RESP_GRP
GO