CREATE TABLE B_MOBILEAPP_CONFIG (
  APP_CODE    VARCHAR2(150 CHAR) NOT NULL,
  PLATFORM    VARCHAR2(150 CHAR) NOT NULL,
  PARAMS      CLOB               NOT NULL,
  DATE_CREATE DATE               NOT NULL,
  PRIMARY KEY (APP_CODE, PLATFORM)
)
/
CREATE TABLE B_MOBILEAPP_APP (
  CODE           VARCHAR2(50 CHAR) NOT NULL,
  SHORT_NAME     VARCHAR2(50 CHAR) NOT NULL,
  NAME           VARCHAR2(50 CHAR) NOT NULL,
  DESCRIPTION    CLOB              NOT NULL,
  FILES          CLOB              NOT NULL,
  LAUNCH_ICONS   CLOB              NOT NULL,
  LAUNCH_SCREENS CLOB              NOT NULL,
  FOLDER         VARCHAR2(50 CHAR) NOT NULL,
  DATE_CREATE    DATE              NOT NULL,
  PRIMARY KEY (CODE)
)
/