DROP TABLE B_IM_CHAT CASCADE CONSTRAINTS
/
DROP TABLE B_IM_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_IM_RELATION CASCADE CONSTRAINTS
/
DROP TABLE B_IM_RECENT CASCADE CONSTRAINTS
/
DROP TABLE B_IM_STATUS CASCADE CONSTRAINTS
/
DROP TABLE B_IM_MESSAGE_PARAM CASCADE CONSTRAINTS
/
DROP TABLE B_IM_BOT CASCADE CONSTRAINTS
/
DROP TABLE B_IM_BOT_CHAT CASCADE CONSTRAINTS
/
DROP TABLE B_IM_BOT_TOKEN CASCADE CONSTRAINTS
/
DROP TABLE B_IM_COMMAND CASCADE CONSTRAINTS
/
DROP TABLE B_IM_COMMAND_LANG CASCADE CONSTRAINTS
/
DROP TABLE B_IM_ALIAS CASCADE CONSTRAINTS
/
DROP TABLE B_IM_EXTERNAL_AVATAR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_IM_CHAT
/
DROP SEQUENCE SQ_B_IM_MESSAGE
/
DROP SEQUENCE SQ_B_IM_MESSAGE_PARAM
/
DROP SEQUENCE SQ_B_IM_RELATION
/
DROP SEQUENCE SQ_B_IM_RECENT
/
DROP SEQUENCE SQ_B_IM_BOT
/
DROP SEQUENCE SQ_B_IM_BOT_CHAT
/
DROP SEQUENCE SQ_B_IM_BOT_TOKEN
/
DROP SEQUENCE SQ_B_IM_COMMAND
/
DROP SEQUENCE SQ_B_IM_COMMAND_LANG
/
DROP SEQUENCE SQ_B_IM_ALIAS
/
DROP SEQUENCE SQ_B_IM_EXTERNAL_AVATAR
/
