DROP TABLE B_TICKET
GO
DROP TABLE B_TICKET_DICTIONARY
GO
DROP TABLE B_TICKET_DICTIONARY_2_SITE
GO
DROP TABLE B_TICKET_MESSAGE
GO
DROP TABLE B_TICKET_MESSAGE_2_FILE
GO
DROP TABLE B_TICKET_ONLINE
GO
DROP TABLE B_TICKET_SLA
GO
DROP TABLE B_TICKET_SLA_2_SITE
GO
DROP TABLE B_TICKET_SLA_2_CATEGORY
GO
DROP TABLE B_TICKET_SLA_2_CRITICALITY
GO
DROP TABLE B_TICKET_SLA_2_MARK
GO
DROP TABLE B_TICKET_SLA_2_USER_GROUP
GO
DROP TABLE B_TICKET_SLA_SHEDULE
GO
DROP TABLE B_TICKET_UGROUPS
GO
DROP TABLE B_TICKET_USER_UGROUP
GO
DROP TABLE B_TICKET_SUPERCOUPONS
GO
DROP TABLE B_TICKET_SUPERCOUPONS_LOG
GO

DROP TABLE b_ticket_timetable
GO
DROP TABLE b_ticket_holidays
GO
DROP TABLE b_ticket_sla_2_holidays
GO
DROP TABLE b_ticket_search
GO
DROP TABLE b_ticket_timetable_cache
GO
