INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (68, 'en', 'Big grin')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (69, 'en', 'Smile')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (70, 'en', 'Sad')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (71, 'en', 'Surprised')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (72, 'en', 'Cool')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (74, 'en', 'Embaressed')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (73, 'en', 'Kiss')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (75, 'en', 'Crying')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (76, 'en', 'Angry')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (77, 'en', 'Wink')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (78, 'en', 'Exclamation')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (79, 'en', 'Question')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (80, 'en', 'Idea')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (81, 'en', 'Speechless')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (82, 'en', 'Skeptical')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (83, 'en', 'Note')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (84, 'en', 'Direction')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (85, 'en', 'Idea')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (86, 'en', 'Attention')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (87, 'en', 'Question')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (88, 'en', 'Thumbs Down')
GO
INSERT INTO B_FORUM_SMILE_LANG (SMILE_ID,LID,NAME) VALUES (89, 'en', 'Thumbs Up')
GO