DROP TABLE B_CONTROLLER_AUTH_GRANT
GO
DROP TABLE B_CONTROLLER_AUTH_LOG
GO
DROP TABLE B_CONTROLLER_GROUP_MAP
GO
DROP TABLE B_CONTROLLER_COUNTER_VALUE
GO
DROP TABLE B_CONTROLLER_COUNTER_GROUP
GO
DROP TABLE B_CONTROLLER_COUNTER
GO
DROP TABLE B_CONTROLLER_LOG
GO
DROP TABLE B_CONTROLLER_TASK
GO
DROP TABLE B_CONTROLLER_COMMAND
GO
DROP TABLE B_CONTROLLER_MEMBER_LOG
GO
DROP TABLE B_CONTROLLER_MEMBER
GO
DROP TABLE B_CONTROLLER_GROUP
GO
