DROP TABLE B_PULL_STACK CASCADE CONSTRAINTS
/
DROP TABLE B_PULL_CHANNEL CASCADE CONSTRAINTS
/
DROP TABLE B_PULL_PUSH CASCADE CONSTRAINTS
/
DROP TABLE B_PULL_PUSH_QUEUE CASCADE CONSTRAINTS
/
DROP TABLE B_PULL_WATCH CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PULL_STACK
/
DROP SEQUENCE SQ_B_PULL_CHANNEL
/
DROP SEQUENCE SQ_B_PULL_PUSH
/
DROP SEQUENCE SQ_B_PULL_PUSH_QUEUE
/
DROP SEQUENCE SQ_B_PULL_WATCH
/