CREATE TABLE B_BITRIXCLOUD_OPTION
(
	ID INT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(50) NOT NULL,
	SORT INT NOT NULL,
	PARAM_KEY VARCHAR(50),
	PARAM_VALUE VARCHAR(200)
)
GO
ALTER TABLE B_BITRIXCLOUD_OPTION ADD CONSTRAINT PK_B_BITRIXCLOUD_OPTION PRIMARY KEY (ID)
GO
CREATE INDEX IX_B_BITRIXCLOUD_OPTION_1 on B_BITRIXCLOUD_OPTION(NAME);
GO