DROP TABLE B_DISK_STORAGE
GO
DROP TABLE B_DISK_OBJECT
GO
DROP TABLE B_DISK_OBJECT_LOCK
GO
DROP TABLE B_DISK_OBJECT_TTL
GO
DROP TABLE B_DISK_OBJECT_PATH
GO
DROP TABLE B_DISK_VERSION
GO
DROP TABLE B_DISK_RIGHT
GO
DROP TABLE B_DISK_SIMPLE_RIGHT
GO
DROP TABLE B_DISK_ATTACHED_OBJECT
GO
DROP TABLE B_DISK_EXTERNAL_LINK
GO
DROP TABLE B_DISK_SHARING
GO
DROP TABLE B_DISK_EDIT_SESSION
GO
DROP TABLE B_DISK_SHOW_SESSION
GO
DROP TABLE B_DISK_TMP_FILE
GO
DROP TABLE B_DISK_DELETED_LOG
GO
DROP TABLE B_DISK_CLOUD_IMPORT
GO
DROP TABLE B_DISK_RECENTLY_USED
GO
