DROP TABLE B_VOXIMPLANT_STATISTIC
GO
DROP TABLE B_VOXIMPLANT_PHONE
GO
DROP TABLE B_VOXIMPLANT_CALL
GO
DROP TABLE B_VOXIMPLANT_SIP
GO
DROP TABLE B_VOXIMPLANT_CONFIG
GO
DROP TABLE B_VOXIMPLANT_QUEUE
GO
DROP TABLE B_VOXIMPLANT_BLACKLIST
GO
DROP TABLE B_VOXIMPLANT_ROLE
GO
DROP TABLE B_VOXIMPLANT_ROLE_PERMISSION
GO
DROP TABLE B_VOXIMPLANT_ROLE_ACCESS
GO