SET IDENTITY_INSERT B_STAT_BROWSER ON
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (1, 'Mozilla%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (2, 'Opera%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (3, '%Netscape%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (4, '%Mosaic%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (5, '%AOL%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (6, '%Lynx%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (7, '%Avant Browser%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (8, '%Firefox/%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (9, '%SonyEricsson%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (10, '%Nokia%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (11, '%SAMSUNG%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (12, '%Microsoft Pocket Internet Explorer%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (13, '%Konqueror%')
GO
INSERT INTO B_STAT_BROWSER (ID, USER_AGENT) VALUES (14, '%RSS%Reader%')
GO
SET IDENTITY_INSERT B_STAT_BROWSER OFF
GO