TRUNCATE TABLE B_STAT_ADV
GO
TRUNCATE TABLE B_STAT_ADV_SEARCHER
GO
TRUNCATE TABLE B_STAT_ADV_EVENT
GO
TRUNCATE TABLE B_STAT_ADV_GUEST
GO
TRUNCATE TABLE B_STAT_ADV_PAGE
GO
TRUNCATE TABLE B_STAT_ADV_SEARCHER
GO
TRUNCATE TABLE B_STAT_DAY
GO
TRUNCATE TABLE B_STAT_DAY_SITE
GO
TRUNCATE TABLE B_STAT_EVENT
GO
TRUNCATE TABLE B_STAT_EVENT_DAY
GO
TRUNCATE TABLE B_STAT_EVENT_LIST
GO
TRUNCATE TABLE B_STAT_GUEST
GO
TRUNCATE TABLE B_STAT_HIT
GO
TRUNCATE TABLE B_STAT_SEARCHER_HIT
GO
TRUNCATE TABLE B_STAT_PHRASE_LIST
GO
TRUNCATE TABLE B_STAT_REFERER
GO
TRUNCATE TABLE B_STAT_REFERER_LIST
GO
UPDATE B_STAT_SEARCHER SET
	DATE_CLEANUP=NULL,
	TOTAL_HITS=0

GO
TRUNCATE TABLE B_STAT_SEARCHER_DAY
GO
TRUNCATE TABLE B_STAT_SESSION
GO
TRUNCATE TABLE B_STAT_ADV_DAY
GO
TRUNCATE TABLE B_STAT_ADV_EVENT_DAY
GO
UPDATE B_STAT_COUNTRY SET
	SESSIONS=0,
	HITS=0,
	NEW_GUESTS=0,
	C_EVENTS=0

GO
TRUNCATE TABLE B_STAT_COUNTRY_DAY
GO
UPDATE B_STAT_CITY SET
	SESSIONS=0,
	HITS=0,
	NEW_GUESTS=0,
	C_EVENTS=0

GO
TRUNCATE TABLE B_STAT_CITY_DAY
GO

TRUNCATE TABLE B_STAT_PATH
GO
TRUNCATE TABLE B_STAT_PATH_CACHE
GO
TRUNCATE TABLE B_STAT_PATH_ADV
GO

TRUNCATE TABLE B_STAT_PAGE
GO
TRUNCATE TABLE B_STAT_PAGE_ADV
GO
