DROP TABLE B_STAT_ADV
GO
DROP TABLE B_STAT_ADV_EVENT
GO
DROP TABLE B_STAT_ADV_GUEST
GO
DROP TABLE B_STAT_ADV_PAGE
GO
DROP TABLE B_STAT_DAY
GO
DROP TABLE B_STAT_DAY_SITE
GO
DROP TABLE B_STAT_EVENT
GO
DROP TABLE B_STAT_EVENT_DAY
GO
DROP TABLE B_STAT_EVENT_LIST
GO
DROP TABLE B_STAT_GUEST
GO
DROP TABLE B_STAT_HIT
GO
DROP TABLE B_STAT_SEARCHER_HIT
GO
DROP TABLE B_STAT_PHRASE_LIST
GO
DROP TABLE B_STAT_REFERER_LIST
GO
DROP TABLE B_STAT_SEARCHER
GO
DROP TABLE B_STAT_SEARCHER_PARAMS
GO
DROP TABLE B_STAT_SESSION
GO
DROP TABLE B_STAT_PAGE
GO
DROP TABLE B_STOP_LIST
GO
DROP TABLE B_STAT_ADV_SEARCHER
GO
DROP TABLE B_STAT_BROWSER
GO
DROP TABLE B_STAT_ADV_DAY
GO
DROP TABLE B_STAT_ADV_EVENT_DAY
GO
DROP TABLE B_STAT_SEARCHER_DAY
GO
DROP TABLE B_STAT_REFERER
GO
DROP TABLE B_STAT_SESSION_DATA
GO
DROP TABLE B_STAT_CITY_IP
GO
DROP TABLE B_STAT_CITY_DAY
GO
DROP TABLE B_STAT_CITY
GO
DROP TABLE B_STAT_COUNTRY
GO
DROP TABLE B_STAT_COUNTRY_DAY
GO
DROP TABLE B_STAT_PATH
GO
DROP TABLE B_STAT_PATH_ADV
GO
DROP TABLE B_STAT_PATH_CACHE
GO
DROP TABLE B_STAT_PAGE_ADV
GO
DROP TABLE B_STAT_DDL
GO
