INSERT INTO B_STAT_BROWSER VALUES (1, '%Mozilla%')
/
INSERT INTO B_STAT_BROWSER VALUES (2, '%Opera%')
/
INSERT INTO B_STAT_BROWSER VALUES (3, '%Netscape%')
/
INSERT INTO B_STAT_BROWSER VALUES (4, '%Mosaic%')
/
INSERT INTO B_STAT_BROWSER VALUES (5, '%AOL%')
/
INSERT INTO B_STAT_BROWSER VALUES (6, '%Lynx%')
/
INSERT INTO B_STAT_BROWSER VALUES (7, '%Avant Browser%')
/
INSERT INTO B_STAT_BROWSER VALUES (8, '%Firefox/%')
/
INSERT INTO B_STAT_BROWSER VALUES (9, '%SonyEricsson%')
/
INSERT INTO B_STAT_BROWSER VALUES (10, '%Nokia%')
/
INSERT INTO B_STAT_BROWSER VALUES (11, '%SAMSUNG%')
/
INSERT INTO B_STAT_BROWSER VALUES (12, '%Microsoft Pocket Internet Explorer%')
/
INSERT INTO B_STAT_BROWSER VALUES (13, '%Konqueror%')
/
INSERT INTO B_STAT_BROWSER VALUES (14, '%RSS%Reader%')
/
DROP SEQUENCE SQ_B_STAT_BROWSER
/
CREATE SEQUENCE SQ_B_STAT_BROWSER START WITH 15
/



