TRUNCATE TABLE B_STAT_ADV
/
TRUNCATE TABLE B_STAT_ADV_SEARCHER
/
TRUNCATE TABLE B_STAT_ADV_DAY
/
TRUNCATE TABLE B_STAT_ADV_EVENT
/
TRUNCATE TABLE B_STAT_ADV_GUEST
/
TRUNCATE TABLE B_STAT_ADV_PAGE
/
TRUNCATE TABLE B_STAT_ADV_SEARCHER
/
TRUNCATE TABLE B_STAT_DAY
/
TRUNCATE TABLE B_STAT_DAY_SITE
/
TRUNCATE TABLE B_STAT_EVENT
/
TRUNCATE TABLE B_STAT_EVENT_DAY
/
TRUNCATE TABLE B_STAT_EVENT_LIST
/
TRUNCATE TABLE B_STAT_GUEST
/
TRUNCATE TABLE B_STAT_HIT
/
TRUNCATE TABLE B_STAT_SEARCHER_HIT
/
TRUNCATE TABLE B_STAT_PHRASE_LIST
/
TRUNCATE TABLE B_STAT_REFERER
/
TRUNCATE TABLE B_STAT_REFERER_LIST
/
UPDATE B_STAT_SEARCHER SET
	DATE_CLEANUP=NULL,
	TOTAL_HITS=0
/
TRUNCATE TABLE B_STAT_SEARCHER_DAY
/
TRUNCATE TABLE B_STAT_SESSION
/
TRUNCATE TABLE B_STAT_PAGE
/
TRUNCATE TABLE B_STAT_ADV_EVENT_DAY
/
UPDATE B_STAT_COUNTRY SET
	SESSIONS=0,
	HITS=0,
	NEW_GUESTS=0,
	C_EVENTS=0
/
TRUNCATE TABLE B_STAT_COUNTRY_DAY
/
UPDATE B_STAT_CITY SET
	SESSIONS=0,
	HITS=0,
	NEW_GUESTS=0,
	C_EVENTS=0
/
TRUNCATE TABLE B_STAT_CITY_DAY
/
TRUNCATE TABLE B_STAT_PATH
/
TRUNCATE TABLE B_STAT_PATH_CACHE
/
TRUNCATE TABLE B_STAT_PATH_ADV
/
TRUNCATE TABLE B_STAT_PAGE_ADV
/