DROP TABLE B_STAT_ADV CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV
/

DROP TABLE B_STAT_ADV_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_DAY
/

DROP TABLE B_STAT_ADV_EVENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_EVENT
/

DROP TABLE B_STAT_ADV_EVENT_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_EVENT_DAY
/

DROP TABLE B_STAT_ADV_GUEST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_GUEST
/

DROP TABLE B_STAT_ADV_PAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_PAGE
/

DROP TABLE B_STAT_ADV_SEARCHER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_ADV_SEARCHER
/

DROP TABLE B_STAT_BROWSER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_BROWSER
/

DROP TABLE B_STAT_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_DAY
/

DROP TABLE B_STAT_DAY_SITE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_DAY_SITE
/

DROP TABLE B_STAT_EVENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_EVENT
/

DROP TABLE B_STAT_EVENT_DAY  CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_EVENT_DAY
/

DROP TABLE B_STAT_EVENT_LIST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_EVENT_LIST
/

DROP TABLE B_STAT_GUEST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_GUEST
/

DROP TABLE B_STAT_HIT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_HIT
/

DROP TABLE B_STAT_SEARCHER_HIT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SEARCHER_HIT
/

DROP TABLE B_STAT_PHRASE_LIST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PHRASE_LIST
/

DROP TABLE B_STAT_REFERER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_REFERER
/

DROP TABLE B_STAT_REFERER_LIST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_REFERER_LIST
/

DROP TABLE B_STAT_SEARCHER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SEARCHER
/

DROP TABLE B_STAT_SEARCHER_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SEARCHER_DAY
/

DROP TABLE B_STAT_SEARCHER_PARAMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SEARCHER_PARAMS
/

DROP TABLE B_STAT_SESSION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SESSION
/

DROP TABLE B_STAT_SESSION_DATA CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_SESSION_DATA
/

DROP TABLE B_STAT_PAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PAGE
/

DROP TABLE B_STOP_LIST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STOP_LIST
/

DROP TABLE B_STAT_CITY_IP
/
DROP TABLE B_STAT_CITY_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_CITY_DAY
/
DROP TABLE B_STAT_CITY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_CITY
/

DROP TABLE B_STAT_COUNTRY CASCADE CONSTRAINTS
/
DROP TABLE B_STAT_COUNTRY_DAY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_COUNTRY_DAY
/

DROP TABLE B_STAT_PATH CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PATH
/
DROP TABLE B_STAT_PATH_ADV CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PATH_ADV
/
DROP TABLE B_STAT_PATH_CACHE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PATH_CACHE
/

DROP TABLE B_STAT_PAGE_ADV  CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_PAGE_ADV
/

DROP TABLE B_STAT_DDL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_STAT_DDL
/
