DROP TABLE B_BLOG_SITE_PATH
GO
DROP TABLE B_BLOG
GO
DROP TABLE B_BLOG_GROUP
GO
DROP TABLE B_BLOG_POST
GO
DROP TABLE B_BLOG_CATEGORY
GO
DROP TABLE B_BLOG_COMMENT
GO
DROP TABLE B_BLOG_USER
GO
DROP TABLE B_BLOG_USER_GROUP
GO
DROP TABLE B_BLOG_USER2USER_GROUP
GO
DROP TABLE B_BLOG_USER_GROUP_PERMS
GO
DROP TABLE B_BLOG_TRACKBACK
GO
DROP TABLE B_BLOG_USER2BLOG
GO
DROP TABLE B_BLOG_IMAGE
GO
DROP TABLE B_BLOG_POST_CATEGORY
GO
DROP TABLE B_BLOG_SOCNET
GO
DROP TABLE B_BLOG_SOCNET_RIGHTS
GO
DROP TABLE B_BLOG_POST_PARAM
GO