DROP TABLE B_CATALOG_CURRENCY CASCADE CONSTRAINTS
/

DROP TABLE B_CATALOG_CURRENCY_LANG CASCADE CONSTRAINTS
/

DROP TABLE B_CATALOG_CURRENCY_RATE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_CURRENCY_RATE
/