INSERT INTO B_FORUM_PM_FOLDER (TITLE, USER_ID, SORT) VALUES ('SYSTEM_FOLDER_1', 0, 0)
GO
INSERT INTO B_FORUM_PM_FOLDER (TITLE, USER_ID, SORT) VALUES ('SYSTEM_FOLDER_2', 0, 0)
GO
INSERT INTO B_FORUM_PM_FOLDER (TITLE, USER_ID, SORT) VALUES ('SYSTEM_FOLDER_3', 0, 0)
GO
INSERT INTO B_FORUM_PM_FOLDER (TITLE, USER_ID, SORT) VALUES ('SYSTEM_FOLDER_4', 0, 0)
GO