SET IDENTITY_INSERT B_FORUM_SMILE ON
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (68, 'S', ':D :-D', 'icon_biggrin.png', 'FICON_BIGGRIN', 'N', 30, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (69, 'S', ':) :-)', 'icon_smile.png', 'FICON_SMILE', 'N', 10, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (70, 'S', ':( :-(', 'icon_sad.png', 'FICON_SAD', 'N', 50, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (71, 'S', ':o :-o :shock:', 'icon_eek.png', 'FICON_EEK', 'N', 90, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (72, 'S', '8) 8-)', 'icon_cool.png', 'FICON_COOL', 'N', 40, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (73, 'S', ':{} :-{}', 'icon_kiss.png', 'FICON_KISS', 'N', 110, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (74, 'S', ':oops:', 'icon_redface.png', 'FICON_REDFACE', 'Y', 100, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (75, 'S', ':cry: :~(', 'icon_cry.png', 'FICON_CRY', 'Y', 70, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (76, 'S', ':evil: >:-<', 'icon_evil.png', 'FICON_EVIL', 'N', 80, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (77, 'S', ';) ;-)', 'icon_wink.png', 'FICON_WINK', 'N', 20, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (78, 'S', ':!:', 'icon_exclaim.png', 'FICON_EXCLAIM', 'Y', 130, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (79, 'S', ':?:', 'icon_question.png', 'FICON_QUESTION', 'Y', 120, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (80, 'S', ':idea:', 'icon_idea.png', 'FICON_IDEA', 'Y', 140, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (81, 'S', ':| :-|', 'icon_neutral.png', 'FICON_NEUTRAL', 'N', 60, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (82, 'S', ':\  :-\  :/ :-/', 'icon_confuse.png', 'FICON_CONFUSE', 'N', 60, 16, 16)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (83, 'I', '', 'icon1.gif', 'FICON_NOTE', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (84, 'I', '', 'icon2.gif', 'FICON_DIRRECTION', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (85, 'I', '', 'icon3.gif', 'FICON_IDEA2', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (86, 'I', '', 'icon4.gif', 'FICON_ATTANSION', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (87, 'I', '', 'icon5.gif', 'FICON_QUESTION2', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (88, 'I', '', 'icon6.gif', 'FICON_BAD', 'Y', 150, 15, 15)
GO
INSERT INTO B_FORUM_SMILE (ID,TYPE,TYPING,IMAGE,DESCRIPTION,CLICKABLE,SORT,IMAGE_WIDTH,IMAGE_HEIGHT) VALUES (89, 'I', '', 'icon7.gif', 'FICON_GOOD', 'Y', 150, 15, 15)
GO
SET IDENTITY_INSERT B_FORUM_SMILE OFF
GO