DELETE FROM B_FORUM_MESSAGE
GO
DROP TABLE B_FORUM_MESSAGE
GO
DELETE FROM B_FORUM_FILE
GO
DROP TABLE B_FORUM_FILE
GO
DELETE FROM B_FORUM_SUBSCRIBE
GO
DROP TABLE B_FORUM_SUBSCRIBE
GO
DELETE FROM B_FORUM_PERMS
GO
DROP TABLE B_FORUM_PERMS
GO
DELETE FROM B_FORUM_TOPIC
GO
DROP TABLE B_FORUM_TOPIC
GO
DELETE FROM B_FORUM
GO
DROP TABLE B_FORUM
GO
DELETE FROM B_FORUM_USER
GO
DROP TABLE B_FORUM_USER
GO
DROP TABLE B_FORUM_RANK
GO
DROP TABLE B_FORUM_RANK_LANG
GO
DROP TABLE B_FORUM_GROUP
GO
DROP TABLE B_FORUM_GROUP_LANG
GO
DROP TABLE B_FORUM_POINTS
GO
DROP TABLE B_FORUM_POINTS_LANG
GO
DROP TABLE B_FORUM_POINTS2POST
GO
DROP TABLE B_FORUM_USER_POINTS
GO
DROP TABLE B_FORUM2SITE
GO
DROP TABLE B_FORUM_PRIVATE_MESSAGE
GO
DROP TABLE B_FORUM_PM_FOLDER
GO
DROP TABLE B_FORUM_FILTER
GO
DROP TABLE B_FORUM_DICTIONARY
GO
DROP TABLE B_FORUM_LETTER
GO
DROP TABLE B_FORUM_USER_TOPIC
GO
DROP TABLE B_FORUM_USER_FORUM
GO
DROP TABLE B_FORUM_STAT
GO
DROP TABLE B_FORUM_EMAIL
GO