DROP SEQUENCE SQ_B_WORKFLOW_DOCUMENT
/
DROP SEQUENCE SQ_B_WORKFLOW_FILE
/
DROP SEQUENCE SQ_B_WORKFLOW_LOG
/
DROP SEQUENCE SQ_B_WORKFLOW_MOVE
/
DROP SEQUENCE SQ_B_WORKFLOW_PREVIEW
/
DROP SEQUENCE SQ_B_WORKFLOW_STATUS
/
DROP SEQUENCE SQ_B_WORKFLOW_STATUS2GROUP
/
DROP TABLE B_WORKFLOW_FILE CASCADE CONSTRAINTS 
/
DROP TABLE B_WORKFLOW_LOG CASCADE CONSTRAINTS
/ 
DROP TABLE B_WORKFLOW_MOVE CASCADE CONSTRAINTS 
/
DROP TABLE B_WORKFLOW_PREVIEW CASCADE CONSTRAINTS 
/
DROP TABLE B_WORKFLOW_STATUS2GROUP CASCADE CONSTRAINTS 
/
DROP TABLE B_WORKFLOW_DOCUMENT CASCADE CONSTRAINTS 
/
DROP TABLE B_WORKFLOW_STATUS CASCADE CONSTRAINTS 
/
