CREATE TABLE B_IDEA_EMAIL_SUBSCRIBE
(
	USER_ID INT NOT NULL,
	SUBSCRIBE_TYPE VARCHAR(32) NOT NULL,
	ENTITY_TYPE VARCHAR(32) NOT NULL,
	ENTITY_CODE VARCHAR(255) NOT NULL
)
GO
ALTER TABLE B_IDEA_EMAIL_SUBSCRIBE ADD CONSTRAINT PK_B_IDEA_EMAIL_SUBSCRIBE PRIMARY KEY (USER_ID, ENTITY_TYPE, ENTITY_CODE)
GO
CREATE INDEX IX_B_IDEA_EMAIL_SUBSCRIBE ON B_IDEA_EMAIL_SUBSCRIBE (SUBSCRIBE_TYPE, ENTITY_TYPE, ENTITY_CODE)
GO