CREATE TABLE B_IDEA_EMAIL_SUBSCRIBE
(
	USER_ID NUMBER(18) NOT NULL,
	SUBSCRIBE_TYPE VARCHAR2(32 CHAR) NOT NULL,
	ENTITY_TYPE varchar2(32 CHAR) NOT NULL ,
	ENTITY_CODE varchar2(255 CHAR) NOT NULL,
	PRIMARY KEY(USER_ID, ENTITY_TYPE, ENTITY_CODE)
)
/
CREATE INDEX IX_B_IDEA_EMAIL_SUBSCRIBE ON B_IDEA_EMAIL_SUBSCRIBE(SUBSCRIBE_TYPE, ENTITY_TYPE, ENTITY_CODE)
/