DROP TABLE B_BP_WORKFLOW_TEMPLATE
GO
DROP TABLE B_BP_WORKFLOW_STATE
GO
DROP TABLE B_BP_WORKFLOW_PERMISSIONS
GO
DROP TABLE B_BP_WORKFLOW_INSTANCE
GO
DROP TABLE B_BP_TRACKING
GO
DROP TABLE B_BP_TASK
GO
DROP TABLE B_BP_TASK_USER
GO
DROP TABLE B_BP_HISTORY
GO
DROP TABLE B_BP_WORKFLOW_STATE_IDENTIFY
GO
DROP TABLE B_BP_REST_ACTIVITY
GO
DROP TABLE B_BP_SCHEDULER_EVENT
GO
