DROP TABLE B_SALE_LANG CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_FUSER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_FUSER
/

DROP TABLE B_SALE_BASKET CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_BASKET
/

DROP TABLE B_SALE_BASKET_PROPS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_BASKET_PROPS
/

DROP TABLE B_SALE_ORDER_TAX CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_TAX
/

DROP TABLE B_SALE_TAX_RATE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TAX_RATE
/

DROP TABLE B_SALE_TAX2LOCATION CASCADE CONSTRAINTS
/
DROP TABLE B_SALE_TAX_EXEMPT2GROUP CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_TAX CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TAX
/

DROP TABLE B_SALE_PAY_SYSTEM_ES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_PAY_SYSTEM_ES
/

DROP TABLE B_SALE_ORDER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER
/

DROP TABLE B_SALE_PERSON_TYPE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_PERSON_TYPE
/

DROP TABLE B_SALE_ORDER_PROPS_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PROPS_GROUP
/

DROP TABLE B_SALE_ORDER_PROPS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PROPS
/

DROP TABLE B_SALE_ORDER_PROPS_VALUE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PROPS_VALUE
/

DROP TABLE B_SALE_ORDER_PROPS_VARIANT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PROPS_VARIANT
/

DROP TABLE B_SALE_ORDER_PROPS_RELATION CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_PAY_SYSTEM_ACTION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_PAY_SYSTEM_ACTION
/

DROP TABLE B_SALE_DELIVERY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_DELIVERY
/

DROP TABLE B_SALE_LOC_EXT_SRV CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOC_EXT_SRV
/

DROP TABLE B_SALE_LOC_EXT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOC_EXT
/

DROP TABLE B_SALE_LOC_TYPE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOC_TYPE
/

DROP TABLE B_SALE_LOC_TYPE_NAME CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOC_TYPE_NAME
/

DROP TABLE B_SALE_LOC_2SITE CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_LOC_DEF2SITE CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_LOCATION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOCATION
/

DROP TABLE B_SALE_LOC_NAME CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOC_NAME
/

DROP TABLE B_SALE_LOCATION_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOCATION_GROUP
/

DROP TABLE B_SALE_LOCATION_GROUP_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOCATION_GROUP_LANG
/

DROP TABLE B_SALE_LOCATION2LOCATION_GROUP CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_DELIVERY2LOCATION CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_DISCOUNT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DISCOUNT
/

DROP TABLE B_SALE_DISCOUNT_COUPON CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DISCOUNT_COUPON
/

DROP TABLE B_SALE_DISCOUNT_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DISCOUNT_GROUP
/

DROP TABLE B_SALE_DISCOUNT_MODULE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DISCOUNT_MODULE
/

DROP TABLE B_SALE_DISCOUNT_ENTITIES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DISCOUNT_ENTITIES
/

DROP TABLE B_SALE_ORDER_DISCOUNT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DISCOUNT
/

DROP TABLE B_SALE_ORDER_COUPONS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_COUPONS
/

DROP TABLE B_SALE_ORDER_MODULES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_MODULES
/

DROP TABLE B_SALE_ORDER_RULES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_RULES
/

DROP TABLE B_SALE_ORDER_RULES_DESCR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_RULES_DESCR
/

DROP TABLE B_SALE_ORDER_DISCOUNT_DATA CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DISCOUNT_DATA
/

DROP TABLE B_SALE_ORDER_ROUND CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_ROUND
/

DROP TABLE B_SALE_USER_PROPS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_USER_PROPS
/

DROP TABLE B_SALE_USER_PROPS_VALUE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_USER_PROPS_VALUE
/

DROP TABLE B_SALE_D_IX_ELEMENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_D_IX_ELEMENT
/

DROP TABLE B_SALE_D_IX_SECTION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_D_IX_SECTION
/

DROP TABLE B_SALE_STATUS CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_STATUS_LANG CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_STATUS_GROUP_TASK CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_ORDER_FLAGS2GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_ORDER_FLAGS2GROUP
/

DROP TABLE B_SALE_SITE2GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_SITE2GROUP
/

DROP TABLE B_SALE_USER_ACCOUNT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_USER_ACCOUNT
/

DROP TABLE B_SALE_RECURRING CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_RECURRING
/

DROP TABLE B_SALE_USER_CARDS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_USER_CARDS
/

DROP TABLE B_SALE_USER_TRANSACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_USER_TRANSACT
/

DROP TABLE B_SALE_AUXILIARY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AUXILIARY
/

DROP TABLE B_SALE_AFFILIATE_PLAN CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AFFILIATE_PLAN
/
DROP TABLE B_SALE_AFFILIATE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AFFILIATE
/
DROP TABLE B_SALE_AFFILIATE_PLAN_SECTION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AFFILIATE_PLAN_SECTION
/
DROP TABLE B_SALE_AFFILIATE_TIER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AFFILIATE_TIER
/
DROP TABLE B_SALE_AFFILIATE_TRANSACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_AFFILIATE_TRANSACT
/

DROP TABLE B_SALE_EXPORT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_EXPORT
/

DROP TABLE B_SALE_DELIVERY_HANDLER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DELIVERY_HANDLER
/



DROP TABLE B_SALE_LOCATION_COUNTRY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_COUNTRY
/

DROP TABLE B_SALE_LOCATION_COUNTRY_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_COUNTRY_LANG
/

DROP TABLE B_SALE_LOCATION_CITY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_CITY
/

DROP TABLE B_SALE_LOCATION_CITY_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_CITY_LANG
/

DROP TABLE B_SALE_LOCATION_REGION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_REGION
/

DROP TABLE B_SALE_LOCATION_REGION_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_LOCATION_REGION_LANG
/
DROP TABLE B_SALE_LOCATION_ZIP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_LOCATION_ZIP
/

DROP TABLE B_SALE_PRODUCT2PRODUCT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_PRODUCT2PRODUCT
/
DROP TABLE B_SALE_PERSON_TYPE_SITE CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_VIEWED_PRODUCT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_VIEWED_PRODUCT
/

DROP TABLE B_SALE_ORDER_HISTORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_ORDER_HISTORY
/

DROP TABLE B_SALE_DELIVERY2PAYSYSTEM CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_STORE_BARCODE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_STORE_BARCODE
/

DROP TABLE B_SALE_ORDER_CHANGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_ORDER_CHANGE
/

DROP TABLE B_SALE_ORDER_DELIVERY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DELIVERY
/

DROP TABLE B_SALE_ORDER_DELIVERY_REQ CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DELIVERY_REQ
/

DROP TABLE B_SALE_ORDER_PROCESSING CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_TP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP
/

DROP TABLE B_SALE_BIZVAL CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_BIZVAL_PERSONDOMAIN CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_BIZVAL_CODE_1C CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_ORDER_DELIVERY_ES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DELIVERY_ES
/

DROP TABLE B_SALE_DELIVERY_ES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DELIVERY_ES
/

DROP TABLE B_SALE_SERVICE_RSTR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_SERVICE_RSTR
/

DROP TABLE B_SALE_DELIVERY_SRV CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_DELIVERY_SRV
/

DROP TABLE B_SALE_ORDER_DLV_BASKET CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_DLV_BASKET
/

DROP TABLE B_SALE_TP_MAP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_MAP
/

DROP TABLE B_SALE_TP_MAP_ENTITY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_MAP_ENTITY
/

DROP TABLE B_SALE_TP_EBAY_CAT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_EBAY_CAT
/

DROP TABLE B_SALE_TP_EBAY_CAT_VAR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_EBAY_CAT_VAR
/

DROP TABLE B_SALE_TP_EBAY_FQ CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_EBAY_FQ
/

DROP TABLE B_SALE_TP_EBAY_FR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_EBAY_FR
/

DROP TABLE B_SALE_TP_ORDER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_ORDER
/

DROP TABLE B_SALE_PAY_SYSTEM_ERR_LOG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_PAY_SYSTEM_ERR_LOG
/

DROP TABLE B_SALE_ORDER_PAYMENT_ES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PAYMENT_ES
/

DROP TABLE B_SALE_PAYMENT_ES CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_PAYMENT_ES
/

DROP TABLE B_SALE_PAY_SYSTEM_RSTR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_PAY_SYSTEM_RSTR
/
DROP TABLE B_SALE_GIFT_RELATED_DATA CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_GIFT_RELATED_DATA
/
DROP TABLE B_SALE_YANDEX_SETTINGS CASCADE CONSTRAINTS
/
DROP TABLE B_SALE_HDALN CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_COMPANY CASCADE CONSTRAINTStas
/
DROP SEQUENCE SQ_B_SALE_COMPANY
/
DROP TABLE B_SALE_COMPANY2LOCATION CASCADE CONSTRAINTS
/
DROP TABLE B_SALE_COMPANY2SERVICE CASCADE CONSTRAINTS
/

DROP TABLE B_SALE_ORDER_PAYMENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_PAYMENT

DROP TABLE B_SALE_ENTITY_MARKER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_SALE_ENTITY_MARKER
/

DROP TABLE B_SALE_TP_VK_PROFILE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_VK_PROFILE
/

DROP TABLE B_SALE_TP_VK_LOG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_TP_VK_LOG
/

DROP TABLE B_SALE_ORDER_ARCHIVE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_ORDER_ARCHIVE
/

DROP TABLE B_SALE_BASKET_ARCHIVE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_BASKET_ARCHIVE
/

DROP TABLE B_SALE_COMPANY_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_COMPANY_GROUP
/

DROP TABLE B_SALE_COMPANY_RESP_GRP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SALE_COMPANY_RESP_GRP
/
