ALTER TABLE B_LEARN_COURSE_SITE DROP CONSTRAINT FK_B_LEARN_COURSE1
GO
ALTER TABLE B_LEARN_COURSE_SITE DROP CONSTRAINT FK_B_LEARN_COURSE2
GO
ALTER TABLE B_LEARN_QUESTION DROP CONSTRAINT FK_B_LEARN_QUESTION1
GO
ALTER TABLE B_LEARN_ANSWER DROP CONSTRAINT FK_B_LEARN_ANSWER1
GO
ALTER TABLE B_LEARN_TEST DROP CONSTRAINT FK_B_LEARN_TEST1
GO
ALTER TABLE B_LEARN_TEST DROP CONSTRAINT FK_B_LEARN_TEST2
GO
ALTER TABLE B_LEARN_ATTEMPT DROP CONSTRAINT FK_B_LEARN_ATTEMPT1
GO
ALTER TABLE B_LEARN_TEST_RESULT DROP CONSTRAINT FK_B_LEARN_TEST_RESULT1
GO
ALTER TABLE B_LEARN_TEST_RESULT DROP CONSTRAINT FK_B_LEARN_TEST_RESULT2
GO
ALTER TABLE B_LEARN_GRADEBOOK DROP CONSTRAINT FK_B_LEARN_GRADEBOOK1
GO
ALTER TABLE B_LEARN_CERTIFICATION DROP CONSTRAINT FK_B_LEARN_CERTIFICATION1
GO
ALTER TABLE B_LEARN_TEST_MARK DROP CONSTRAINT FK_B_LEARN_TEST_MARK1
GO

DROP TRIGGER B_LEARN_COURSE_UPDATE
GO
DROP TRIGGER B_LEARN_CHAPTER_UPDATE
GO
DROP TRIGGER B_LEARN_LESSON_UPDATE
GO
DROP TRIGGER B_LEARN_QUESTION_UPDATE
GO
DROP TRIGGER B_LEARN_TEST_UPDATE
GO
DROP TRIGGER B_LEARN_CERTIFICATION_UPDATE
GO

ALTER TABLE B_LEARN_EXCEPTION_LOG NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_PUBLISH_PROHIBITION NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_RIGHTS NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_RIGHTS_ALL NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_LESSON_EDGES NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_COURSE NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_COURSE_SITE NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_CHAPTER NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_LESSON NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_QUESTION NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_ANSWER NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_TEST NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_ATTEMPT NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_TEST_RESULT NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_GRADEBOOK NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_STUDENT NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_CERTIFICATION NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_SITE_PATH NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_TEST_MARK NOCHECK CONSTRAINT ALL
GO
ALTER TABLE B_LEARN_GROUPS NOCHECK CONSTRAINT ALL
GO

DROP TABLE B_LEARN_EXCEPTION_LOG
GO
DROP TABLE B_LEARN_PUBLISH_PROHIBITION
GO
DROP TABLE B_LEARN_RIGHTS
GO
DROP TABLE B_LEARN_RIGHTS_ALL
GO
DROP TABLE B_LEARN_LESSON_EDGES
GO
DROP TABLE B_LEARN_COURSE
GO
DROP TABLE B_LEARN_COURSE_SITE
GO
DROP TABLE B_LEARN_CHAPTER
GO
DROP TABLE B_LEARN_LESSON
GO
DROP TABLE B_LEARN_QUESTION
GO
DROP TABLE B_LEARN_ANSWER
GO
DROP TABLE B_LEARN_TEST
GO
DROP TABLE B_LEARN_ATTEMPT
GO
DROP TABLE B_LEARN_TEST_RESULT
GO
DROP TABLE B_LEARN_GRADEBOOK
GO
DROP TABLE B_LEARN_STUDENT
GO
DROP TABLE B_LEARN_CERTIFICATION
GO
DROP TABLE B_LEARN_SITE_PATH
GO
DROP TABLE B_LEARN_TEST_MARK
GO
DROP TABLE B_LEARN_GROUPS
GO
DROP TABLE B_LEARN_GROUPS_MEMBER
GO
DROP TABLE B_LEARN_GROUPS_LESSON
GO
