DELETE FROM b_agent WHERE MODULE_ID='iblock'
/
DROP TABLE b_iblock_iblock_iprop CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_section_iprop CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_element_iprop CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_iproperty CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_iproperty
/
DROP TABLE b_iblock_type CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_site CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_type_lang CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_fields CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_element_right CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_section_right CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_right
/
DROP TABLE b_iblock_section_property CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_right CASCADE CONSTRAINTS
/
DROP TABLE b_iblock CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock
/
DROP TABLE b_iblock_property  CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_property
/
DROP TABLE b_iblock_section CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_messages CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_section
/
DROP TABLE b_iblock_element_lock CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_element_property CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_element_property
/
DROP TABLE b_iblock_element CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_element
/
DROP TABLE b_iblock_group CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_IBLOCK_RSS
/
DROP TABLE B_IBLOCK_RSS CASCADE CONSTRAINTS
/
DROP TABLE B_IBLOCK_CACHE CASCADE CONSTRAINTS
/
DROP TABLE B_IBLOCK_PROPERTY_ENUM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_IBLOCK_PROPERTY_ENUM
/
DROP TABLE B_IBLOCK_SECTION_ELEMENT CASCADE CONSTRAINTS
/
DROP TABLE B_IBLOCK_SEQUENCE CASCADE CONSTRAINTS
/
DROP TABLE b_iblock_offers_tmp CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_b_iblock_offers_tmp
/