
CREATE TABLE b_abtest (
	ID NUMBER(18) NOT NULL,
	SITE_ID VARCHAR2(255 CHAR) NOT NULL,
	ACTIVE CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
	ENABLED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
	NAME VARCHAR2(255 CHAR) NULL,
	DESCR VARCHAR2(2000 CHAR) NULL,
	TEST_DATA VARCHAR2(2000 CHAR) NOT NULL,
	START_DATE DATE NULL,
	STOP_DATE DATE NULL,
	DURATION NUMBER(18) DEFAULT 0 NOT NULL,
	PORTION NUMBER(18) DEFAULT 0 NOT NULL,
	MIN_AMOUNT NUMBER(18) NULL,
	USER_ID NUMBER(18) NULL,
	SORT NUMBER(18) DEFAULT 100 NOT NULL,
	PRIMARY KEY (ID)
)
/
CREATE SEQUENCE sq_b_abtest INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE NOORDER
/

CREATE OR REPLACE TRIGGER b_abtest_insert
BEFORE INSERT
ON b_abtest
FOR EACH ROW
BEGIN
	IF :NEW.ID IS NULL THEN
		SELECT sq_b_abtest.NEXTVAL INTO :NEW.ID FROM dual;
	END IF;
END;
/
