DROP TABLE B_FORUM CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM
/
DROP TABLE B_FORUM_TOPIC CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM_TOPIC
/
DROP TABLE B_FORUM_MESSAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM_MESSAGE
/
DROP TABLE B_FORUM_FILE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_FILE
/
DROP TABLE B_FORUM_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM_USER
/
DROP TABLE B_FORUM_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM_PERMS
/
DROP TABLE B_FORUM_SUBSCRIBE CASCADE CONSTRAINTS
/
DROP SEQUENCE sq_B_FORUM_SUBSCRIBE
/
DROP TABLE B_FORUM_RANK CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_RANK
/
DROP TABLE B_FORUM_RANK_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_RANK_LANG
/
DROP TABLE B_FORUM_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_GROUP
/
DROP TABLE B_FORUM_GROUP_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_GROUP_LANG
/
DROP TABLE B_FORUM_POINTS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_POINTS
/
DROP TABLE B_FORUM_POINTS_LANG CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_POINTS2POST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_POINTS2POST
/
DROP TABLE B_FORUM_USER_POINTS CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM2SITE CASCADE CONSTRAINTS
/

DROP TABLE B_FORUM_PM_FOLDER CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_PRIVATE_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_FILTER CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_DICTIONARY CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_LETTER CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_USER_TOPIC CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_USER_FORUM CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_FORUM_EMAIL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_FORUM_PM_FOLDER
/
DROP SEQUENCE SQ_B_FORUM_PRIVATE_MESSAGE
/
DROP SEQUENCE SQ_B_FORUM_FILTER
/
DROP SEQUENCE SQ_B_FORUM_DICTIONARY
/
DROP SEQUENCE SQ_B_FORUM_LETTER
/
DROP SEQUENCE SQ_B_FORUM_USER_TOPIC
/
DROP SEQUENCE SQ_B_FORUM_STAT
/
DROP SEQUENCE SQ_B_FORUM_USER_FORUM
/
DROP SEQUENCE SQ_B_FORUM_EMAIL
/