DROP TABLE B_SOCIALSERVICES_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SOCIALSERVICES_USER
/
DROP TABLE B_SOCIALSERVICES_MESSAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SOCIALSERVICES_MESSAGE
/
DROP TABLE B_SOCIALSERVICES_USER_LINK CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SOCIALSERVICES_USER_LINK
/
DROP TABLE B_SOCIALSERVICES_AP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_SOCIALSERVICES_AP
/
