CREATE TABLE b_report (
  ID int NOT NULL IDENTITY (1, 1),
  OWNER_ID varchar(20) NULL,
  TITLE varchar(255) NOT NULL,
  DESCRIPTION text NULL,
  CREATED_DATE datetime NOT NULL,
  CREATED_BY int NOT NULL,
  SETTINGS text NULL,
  MARK_DEFAULT smallint NULL,
  CONSTRAINT report_ibpk_1 PRIMARY KEY (ID)
)
GO

CREATE INDEX IX_REPORT_OWNER_ID ON B_REPORT (OWNER_ID)
GO

CREATE TABLE B_REPORT_SHARING (
  ID int NOT NULL IDENTITY (1, 1),
  REPORT_ID int NOT NULL default 0,
  ENTITY varchar(50) NOT NULL,
  RIGHTS varchar(50) NOT NULL,
  CONSTRAINT PK_B_REPORT_SHARING PRIMARY KEY (ID)
)
GO

CREATE INDEX IX_ENTITY ON B_REPORT_SHARING (ENTITY)
GO
CREATE INDEX IX_REPORT_ID ON B_REPORT_SHARING (REPORT_ID)
GO