CREATE TABLE b_search_phrase
(
	ID			INT		NOT NULL IDENTITY(1,1),
	TIMESTAMP_X		DATETIME	NOT NULL,
	SITE_ID			CHAR(2)		NOT NULL,
	RESULT_COUNT		INT		NOT NULL,
	PAGES			INT		NOT NULL,
	SESSION_ID		VARCHAR(32)	NOT NULL,
	PHRASE			VARCHAR(250),
	TAGS			VARCHAR(250),
	URL_TO			VARCHAR(2000),
	URL_TO_404		CHAR(1),
	URL_TO_SITE_ID		CHAR(2),
	STAT_SESS_ID		INT,
	EVENT1			VARCHAR(50)
)
GO
ALTER TABLE b_search_phrase ADD CONSTRAINT PK_B_SEARCH_PHRASE PRIMARY KEY (ID)
GO
CREATE INDEX IND_PK_B_SEARCH_PHRASE_SESS_PH ON b_search_phrase(SESSION_ID, PHRASE)
GO
CREATE INDEX IND_PK_B_SEARCH_PHRASE_SESS_TG ON b_search_phrase(SESSION_ID, TAGS)
GO
CREATE INDEX IND_PK_B_SEARCH_PHRASE_TIME ON b_search_phrase(TIMESTAMP_X)
GO
