DROP TABLE B_CRM_LEAD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_LEAD
/
DROP TABLE B_CRM_DEAL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DEAL
/
DROP TABLE B_CRM_CONTACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_CONTACT
/
DROP TABLE B_CRM_COMPANY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_COMPANY
/
DROP TABLE B_CRM_STATUS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_STATUS
/
DROP TABLE B_CRM_FIELD_MULTI CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_FIELD_MULTI
/
DROP TABLE B_CRM_EVENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EVENT
/
DROP TABLE B_CRM_EVENT_RELATIONS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EVENT_RELATIONS
/
DROP TABLE B_CRM_ENTITY_LOCK CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ENTITY_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ENTITY_PERMS
/
DROP TABLE B_CRM_ROLE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE
/
DROP TABLE B_CRM_ROLE_PERMS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE_PERMS
/
DROP TABLE B_CRM_ROLE_RELATION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ROLE_RELATION
/
DROP TABLE B_CRM_EXTERNAL_SALE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_EXTERNAL_SALE
/
DROP TABLE B_CRM_PRODUCT_ROW_CFG CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_PRODUCT_ROW CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_PRODUCT_ROW
/
DROP TABLE B_CRM_PRODUCT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CATALOG CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_USR_ACT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_ELEM CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_COMM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT_COMM
/
DROP TABLE B_CRM_ACT_BIND CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT_BIND
/
DROP TABLE B_CRM_ACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_ACT
/
DROP TABLE B_CRM_USR_MT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_USR_MT
/
DROP TABLE B_CRM_SL_REL CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_SL_SUBSCR CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_QUOTE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_QUOTE
/
DROP TABLE B_CRM_QUOTE_ELEM CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_BIZ_TYPE CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DP_ORG_MCD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DP_ORG_MCD
/
DROP TABLE B_CRM_DP_COMM_MCD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DP_COMM_MCD
/
DROP TABLE B_CRM_DP_PRSN_MCD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DP_PRSN_MCD
/
DROP TABLE B_CRM_DP_INDEX CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DP_INDEX_MISMATCH CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DP_ENTITY_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DP_ENTITY_HASH CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ADDR CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_STAGE_HISTORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DEAL_STAGE_HISTORY
/
DROP TABLE B_CRM_DEAL_SUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_INV_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_ACT_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONV_MAP CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_LEAD_STATUS_HISTORY CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_LEAD_SUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_LEAD_ACT_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_LEAD_CONV_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_INV_STATUS_HISTORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_INV_STATUS_HISTORY
/
DROP TABLE B_CRM_INVOICE_SUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_REQUISITE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_REQUISITE
/
DROP TABLE B_CRM_PRESET CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_PRESET
/
DROP TABLE B_CRM_REQUISITE_CFG CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_REQUISITE_LINK CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_BANK_DETAIL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_BANK_DETAIL
/
DROP TABLE B_CRM_CONTACT_COMPANY CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_CONTACT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_QUOTE_CONTACT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ENTITY_CFG CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_PS_RQ_CONV_RELATION CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_CATEGORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_DEAL_CATEGORY
/
DROP TABLE B_CRM_WEBFORM CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_WEBFORM
/
DROP TABLE B_CRM_WEBFORM_COUNTER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_WEBFORM_COUNTER
/
DROP TABLE B_CRM_WEBFORM_VIEW CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_WEBFORM_START_EDIT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_WEBFORM_FIELD CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_WEBFORM_FIELD
/
DROP TABLE B_CRM_WEBFORM_FIELD_DEP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_WEBFORM_FIELD_DEP
/
DROP TABLE B_CRM_WEBFORM_FIELD_PRESET CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_WEBFORM_RESULT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_WEBFORM_RESULT
/
DROP TABLE B_CRM_WEBFORM_RESULT_ENTITY CASCADE CONSTRAINTS
/
BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE b_sale_pay_system_ac_bu';
	EXCEPTION
	WHEN OTHERS THEN
	IF SQLCODE != -942 THEN
		RAISE;
	END IF;
END;
/
DROP TABLE B_CRM_COMPANY_ACT_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_COMPANY_ACT_STS_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_COMPANY_ACT_MARK_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_COMPANY_ACT_STM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_COMPANY_ACT_SUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_COMPANY_GROWTH_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_ACT_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_ACT_STS_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_ACT_MARK_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_ACT_STM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_ACT_SUM_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_CONTACT_GROWTH_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_BUTTON CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_UTM CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ENTITY_CHANNEL CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_LEAD_CHANNEL_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_DEAL_CHANNEL_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_ACT_CHANNEL_STAT CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_EXT_CHANNEL_CONNECTOR CASCADE CONSTRAINTS
/
DROP TABLE B_CRM_AUTOMATION_TEMPLATE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_AUTOMATION_TEMPLATE
/
DROP TABLE B_CRM_AUTOMATION_TRIGGER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_AUTOMATION_TRIGGER
/
DROP TABLE B_CRM_KANBAN_SORT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_KANBAN_SORT
/
DROP TABLE B_CRM_KANBAN_SUPERVISOR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CRM_KANBAN_SUPERVISOR
/