CREATE TABLE B_SEO_KEYWORDS
(
	ID int NOT NULL IDENTITY (1, 1),
	SITE_ID CHAR(2) NOT NULL,
	URL varchar(255),
	KEYWORDS text NULL,
)
GO
ALTER TABLE B_SEO_KEYWORDS ADD CONSTRAINT PK_B_SEO_KEYWORDS PRIMARY KEY (ID)
GO
CREATE INDEX IX_B_SEO_KEYWORDS ON B_SEO_KEYWORDS (URL, SITE_ID)
GO

CREATE TABLE B_SEO_SEARCH_ENGINE
(
	ID INT NOT NULL IDENTITY (1, 1),
	CODE VARCHAR(50) NOT NULL,
	ACTIVE CHAR(1) NULL,
	SORT INT NULL,
	NAME VARCHAR(255) NOT NULL,
	CLIENT_ID VARCHAR(255) NULL,
	CLIENT_SECRET VARCHAR(255) NULL,
	REDIRECT_URI VARCHAR(255) NULL,
	SETTINGS TEXT NULL
)
GO
ALTER TABLE B_SEO_SEARCH_ENGINE ADD CONSTRAINT PK_B_SEO_SEARCH_ENGINE PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_SEARCH_ENGINE ADD CONSTRAINT DF_B_SEO_SEARCH_ENGINE_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
ALTER TABLE B_SEO_SEARCH_ENGINE ADD CONSTRAINT DF_B_SEO_SEARCH_ENGINE_SORT DEFAULT 100 FOR SORT
GO
CREATE UNIQUE INDEX UX_B_SEO_SEARCH_ENGINE ON B_SEO_SEARCH_ENGINE (CODE)
GO

INSERT INTO b_seo_search_engine (CODE, ACTIVE, SORT, NAME, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI) VALUES ('google', 'Y', 200, 'Google', '868942902147-qrrd6ce1ajfkpse8ieq4gkpdeanvtnno.apps.googleusercontent.com', 'EItMlJpZLC2WRPKB6QsA5bV9-zo5', 'urn:ietf:wg:oauth:2.0:oob')
GO
INSERT INTO b_seo_search_engine (CODE, ACTIVE, SORT, NAME, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI) VALUES ('yandex', 'Y', 300, 'Yandex', 'f848c7bfc1d34a94ba6d05439f81bbd7', 'da0e73b2d9cc4e809f3170e49cb9df01', 'https://oauth.yandex.ru/verification_code')
GO
INSERT INTO b_seo_search_engine (CODE, ACTIVE, SORT, NAME, CLIENT_ID, CLIENT_SECRET, REDIRECT_URI) VALUES ('yandex_direct', 'Y', 400, 'Yandex.Direct', 'e46a29a748d84036baee1e2ae2a84fc6', '7122987f5a99479bb756d79ed7986e6c', 'https://oauth.yandex.ru/verification_code')
GO

CREATE TABLE B_SEO_SITEMAP
(
	ID INT NOT NULL IDENTITY (1, 1),
	TIMESTAMP_X DATETIME NULL,
	SITE_ID CHAR(2) NOT NULL,
	ACTIVE CHAR(1) NULL,
	NAME VARCHAR(255) NULL,
	DATE_RUN DATETIME NULL,
	SETTINGS TEXT NULL
)
GO
ALTER TABLE B_SEO_SITEMAP ADD CONSTRAINT PK_B_SEO_SITEMAP PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_SITEMAP ADD CONSTRAINT DF_B_SEO_SITEMAP_TIMESTAMP_X DEFAULT GETDATE() FOR TIMESTAMP_X
GO
ALTER TABLE B_SEO_SITEMAP ADD CONSTRAINT DF_B_SEO_SITEMAP_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO

create trigger B_SEO_SITEMAP_UPDATE on B_SEO_SITEMAP for update as
if (not update(TIMESTAMP_X))
begin
	UPDATE B_SEO_SITEMAP SET
		TIMESTAMP_X = GETDATE()
	FROM
		B_SEO_SITEMAP U,
		INSERTED I,
		DELETED D
	WHERE
		U.ID = I.ID
	and U.ID = D.ID
end
GO


CREATE TABLE B_SEO_SITEMAP_RUNTIME
(
	ID INT NOT NULL IDENTITY (1, 1),
	PID INT NOT NULL,
	PROCESSED CHAR(1) NOT NULL,
	ITEM_PATH VARCHAR(700) NULL,
	ITEM_ID INT NULL,
	ITEM_TYPE char(1) NOT NULL,
	ACTIVE char(1) NULL,
	ACTIVE_ELEMENT char(1) NULL
)
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME ADD CONSTRAINT PK_B_SEO_SITEMAP_RUNTIME PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME ADD CONSTRAINT DF_B_SEO_SITEMAP_RUNTIME_PROCESSED DEFAULT 'Y' FOR PROCESSED
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME ADD CONSTRAINT DF_B_SEO_SITEMAP_RUNTIME_ITEM_TYPE DEFAULT 'D' FOR ITEM_TYPE
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME ADD CONSTRAINT DF_BB_SEO_SITEMAP_RUNTIME_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME ADD CONSTRAINT DF_BB_SEO_SITEMAP_RUNTIME_ACTIVE_ELEMENT DEFAULT 'Y' FOR ACTIVE_ELEMENT
GO
CREATE INDEX IX_SEO_SITEMAP_RUNTIME1 ON B_SEO_SITEMAP_RUNTIME (PID, PROCESSED, ITEM_TYPE, ITEM_ID)
GO


CREATE TABLE B_SEO_SITEMAP_IBLOCK
(
	ID INT NOT NULL IDENTITY (1, 1),
	IBLOCK_ID INT NOT NULL,
	SITEMAP_ID INT NOT NULL
)
GO
ALTER TABLE B_SEO_SITEMAP_IBLOCK ADD CONSTRAINT PK_B_SEO_SITEMAP_IBLOCK PRIMARY KEY (ID)
GO
CREATE INDEX IX_B_SEO_SITEMAP_IBLOCK_1 ON B_SEO_SITEMAP_IBLOCK (IBLOCK_ID)
GO
CREATE INDEX IX_B_SEO_SITEMAP_IBLOCK_2 ON B_SEO_SITEMAP_IBLOCK (SITEMAP_ID)
GO


CREATE TABLE B_SEO_SITEMAP_ENTITY
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENTITY_TYPE VARCHAR(255) NOT NULL,
	ENTITY_ID INT NOT NULL,
	SITEMAP_ID INT NOT NULL
)
GO
ALTER TABLE B_SEO_SITEMAP_ENTITY ADD CONSTRAINT PK_B_SEO_SITEMAP_ENTITY PRIMARY KEY (ID)
GO
CREATE INDEX IX_B_SEO_SITEMAP_ENTITY_1 ON B_SEO_SITEMAP_ENTITY (ENTITY_TYPE, ENTITY_ID)
GO
CREATE INDEX IX_B_SEO_SITEMAP_ENTITY_2 ON B_SEO_SITEMAP_ENTITY (SITEMAP_ID)
GO



CREATE TABLE B_SEO_ADV_CAMPAIGN
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	OWNER_ID VARCHAR(255) NOT NULL,
	OWNER_NAME VARCHAR(255) NOT NULL,
	XML_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	LAST_UPDATE DATETIME NULL,
	SETTINGS TEXT NULL
)
GO
ALTER TABLE B_SEO_ADV_CAMPAIGN ADD CONSTRAINT PK_B_SEO_ADV_CAMPAIGN PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_CAMPAIGN ADD CONSTRAINT DF_B_SEO_ADV_CAMPAIGN_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
CREATE UNIQUE INDEX UX_B_SEO_ADV_CAMPAIGN ON B_SEO_ADV_CAMPAIGN (ENGINE_ID, XML_ID)
GO

CREATE TABLE B_SEO_ADV_GROUP
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	OWNER_ID VARCHAR(255) NOT NULL,
	OWNER_NAME VARCHAR(255) NOT NULL,
	XML_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	LAST_UPDATE DATETIME NULL,
	SETTINGS TEXT NULL,
	CAMPAIGN_ID INT NOT NULL
)
GO
ALTER TABLE B_SEO_ADV_GROUP ADD CONSTRAINT PK_B_SEO_ADV_GROUP PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_GROUP ADD CONSTRAINT DF_B_SEO_ADV_GROUP_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
CREATE UNIQUE INDEX UX_B_SEO_ADV_GROUP ON B_SEO_ADV_GROUP (ENGINE_ID, XML_ID)
GO
CREATE INDEX IX_B_SEO_ADV_GROUP1 ON B_SEO_ADV_GROUP (CAMPAIGN_ID)
GO

CREATE TABLE B_SEO_ADV_BANNER
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	OWNER_ID VARCHAR(255) NOT NULL,
	OWNER_NAME VARCHAR(255) NOT NULL,
	XML_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	LAST_UPDATE DATETIME NULL,
	SETTINGS TEXT NULL,
	CAMPAIGN_ID INT NOT NULL,
	GROUP_ID INT NULL,
	AUTO_QUANTITY_OFF CHAR(1) NULL,
	AUTO_QUANTITY_ON CHAR(1) NULL,

)
GO
ALTER TABLE B_SEO_ADV_BANNER ADD CONSTRAINT PK_B_SEO_ADV_BANNER PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_BANNER ADD CONSTRAINT DF_B_SEO_ADV_BANNER_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
ALTER TABLE B_SEO_ADV_BANNER ADD CONSTRAINT DF_B_SEO_ADV_BANNER_AUTO_QUANTITY_OFF DEFAULT 'N' FOR AUTO_QUANTITY_OFF
GO
ALTER TABLE B_SEO_ADV_BANNER ADD CONSTRAINT DF_B_SEO_ADV_BANNER_AUTO_QUANTITY_ON DEFAULT 'N' FOR AUTO_QUANTITY_ON
GO
CREATE UNIQUE INDEX UX_B_SEO_ADV_BANNER ON B_SEO_ADV_BANNER (ENGINE_ID, XML_ID)
GO
CREATE INDEX IX_B_SEO_ADV_BANNER1 ON B_SEO_ADV_BANNER (CAMPAIGN_ID)
GO
CREATE INDEX IX_B_SEO_ADV_BANNER2 ON B_SEO_ADV_BANNER (AUTO_QUANTITY_OFF,AUTO_QUANTITY_ON)
GO


CREATE TABLE B_SEO_ADV_REGION
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	ACTIVE CHAR(1) NOT NULL,
	OWNER_ID VARCHAR(255) NOT NULL,
	OWNER_NAME VARCHAR(255) NOT NULL,
	XML_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	LAST_UPDATE DATETIME NULL,
	SETTINGS TEXT NULL,
	PARENT_ID INT NOT NULL
)
GO
ALTER TABLE B_SEO_ADV_REGION ADD CONSTRAINT PK_B_SEO_ADV_REGION PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_REGION ADD CONSTRAINT DF_B_SEO_ADV_REGION_ACTIVE DEFAULT 'Y' FOR ACTIVE
GO
CREATE UNIQUE INDEX UX_B_SEO_ADV_REGION ON B_SEO_ADV_REGION (ENGINE_ID, XML_ID)
GO
CREATE INDEX IX_B_SEO_ADV_REGION1 ON B_SEO_ADV_REGION (PARENT_ID)
GO


CREATE TABLE B_SEO_ADV_LINK
(
	LINK_TYPE CHAR(1) NOT NULL,
	LINK_ID INT NOT NULL,
	BANNER_ID INT NOT NULL
)
GO
ALTER TABLE B_SEO_ADV_LINK ADD CONSTRAINT PK_B_SEO_ADV_LINK PRIMARY KEY (LINK_TYPE,LINK_ID,BANNER_ID)
GO


CREATE TABLE B_SEO_ADV_ORDER
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	TIMESTAMP_X DATE NOT NULL,
	CAMPAIGN_ID INT NOT NULL,
	BANNER_ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	SUM FLOAT NULL,
	PROCESSED CHAR(1) NULL
)
GO
ALTER TABLE B_SEO_ADV_ORDER ADD CONSTRAINT PK_B_SEO_ADV_ORDER PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_ORDER ADD CONSTRAINT DF_B_SEO_ADV_ORDER_PROCESSED DEFAULT 'N' FOR PROCESSED
GO
CREATE UNIQUE INDEX UX_B_SEO_ADV_ORDER ON B_SEO_ADV_ORDER (ENGINE_ID, CAMPAIGN_ID, BANNER_ID, ORDER_ID)
GO
CREATE INDEX IX_B_SEO_ADV_ORDER1 ON B_SEO_ADV_ORDER (ORDER_ID, PROCESSED)
GO


CREATE TABLE B_SEO_ADV_LOG
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	TIMESTAMP_X DATETIME NOT NULL,
	REQUEST_URI VARCHAR(100) NOT NULL,
	REQUEST_DATA TEXT,
	RESPONSE_TIME FLOAT NOT NULL,
	RESPONSE_STATUS INT,
	RESPONSE_DATA TEXT
)
GO
ALTER TABLE B_SEO_ADV_LOG ADD CONSTRAINT PK_B_SEO_ADV_LOG PRIMARY KEY (ID)
GO
CREATE INDEX IX_B_SEO_ADV_LOG1 ON B_SEO_ADV_LOG (ENGINE_ID)
GO
CREATE INDEX IX_B_SEO_ADV_LOG2 ON B_SEO_ADV_LOG (TIMESTAMP_X)
GO

CREATE TABLE B_SEO_ADV_AUTOLOG
(
	ID INT NOT NULL IDENTITY (1, 1),
	ENGINE_ID INT NOT NULL,
	TIMESTAMP_X DATETIME NOT NULL,
	CAMPAIGN_ID INT NOT NULL,
	CAMPAIGN_XML_ID VARCHAR(255) NOT NULL,
	BANNER_ID INT NOT NULL,
	BANNER_XML_ID VARCHAR(255) NOT NULL,
	CAUSE_CODE INT NULL,
	SUCCESS CHAR(1) NULL
)
GO
ALTER TABLE B_SEO_ADV_AUTOLOG ADD CONSTRAINT PK_B_SEO_ADV_AUTOLOG PRIMARY KEY (ID)
GO
ALTER TABLE B_SEO_ADV_AUTOLOG ADD CONSTRAINT DF_B_SEO_ADV_AUTOLOG_SUCCESS DEFAULT 'Y' FOR SUCCESS
GO
CREATE INDEX IX_B_SEO_ADV_AUTOLOG1 ON B_SEO_ADV_AUTOLOG (ENGINE_ID)
GO
CREATE INDEX IX_B_SEO_ADV_AUTOLOG2 ON B_SEO_ADV_AUTOLOG (TIMESTAMP_X)
GO

CREATE TABLE B_SEO_YANDEX_DIRECT_STAT
	(
	ID INT NOT NULL IDENTITY (1, 1),
	CAMPAIGN_ID INT NOT NULL,
	BANNER_ID INT NOT NULL,
	DATE_DAY DATE NOT NULL,
	CURRENCY CHAR(3) NULL,
	SUM FLOAT NULL,
	SUM_SEARCH FLOAT NULL,
	SUM_CONTEXT FLOAT NULL,
	CLICKS INT NULL,
	CLICKS_SEARCH INT NULL,
	CLICKS_CONTEXT INT NULL,
	SHOWS INT NULL,
	SHOWS_SEARCH INT NULL,
	SHOWS_CONTEXT INT NULL,
)
GO
ALTER TABLE B_SEO_YANDEX_DIRECT_STAT ADD CONSTRAINT PK_B_SEO_YANDEX_DIRECT_STAT PRIMARY KEY (ID)
GO
CREATE UNIQUE INDEX UX_SEO_YANDEX_DIRECT_STAT ON B_SEO_YANDEX_DIRECT_STAT (BANNER_ID,DATE_DAY)
GO
CREATE INDEX IX_SEO_YANDEX_DIRECT_STAT1 ON B_SEO_YANDEX_DIRECT_STAT (CAMPAIGN_ID)
GO

IF OBJECT_ID(N'B_SEO_SERVICE_RTG_QUEUE', N'U') IS NULL
	CREATE TABLE B_SEO_SERVICE_RTG_QUEUE (
		ID INT NOT NULL IDENTITY (1, 1),
		DATE_INSERT DATETIME DEFAULT NULL,
		TYPE VARCHAR(20) NOT NULL,
		ACCOUNT_ID VARCHAR(15) DEFAULT NULL,
		AUDIENCE_ID VARCHAR(15) NOT NULL,
		CONTACT_TYPE VARCHAR(15) NOT NULL,
		VALUE VARCHAR(255) NOT NULL,
		ACTION CHAR(3) NOT NULL,
		DATE_AUTO_REMOVE DATETIME DEFAULT NULL,
		PRIMARY KEY (ID)
	)
GO
IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = N'IX_B_SEO_SRV_RTG_QUEUE_1')
	CREATE INDEX IX_B_SEO_SRV_RTG_QUEUE_1 ON B_SEO_SERVICE_RTG_QUEUE (ACTION, DATE_AUTO_REMOVE)
GO
IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = N'IX_B_SEO_SRV_RTG_QUEUE_2')
	CREATE INDEX IX_B_SEO_SRV_RTG_QUEUE_2 ON B_SEO_SERVICE_RTG_QUEUE (TYPE, ACTION)
GO

IF OBJECT_ID(N'B_SEO_SERVICE_LOG', N'U') IS NULL
	CREATE TABLE B_SEO_SERVICE_LOG (
		ID INT NOT NULL IDENTITY (1, 1),
		DATE_INSERT DATETIME NOT NULL,
		TYPE VARCHAR(20) NOT NULL,
		CODE VARCHAR(20) DEFAULT NULL,
		MESSAGE VARCHAR		(1000) NOT NULL,
		GROUP_ID VARCHAR(20) NOT NULL,
		PRIMARY KEY (ID)
	)
GO