ALTER TABLE B_SEO_KEYWORDS DROP CONSTRAINT PK_B_SEO_KEYWORDS
GO
DROP TABLE B_SEO_KEYWORDS
GO


ALTER TABLE B_SEO_SEARCH_ENGINE DROP CONSTRAINT PK_B_SEO_SEARCH_ENGINE
GO
ALTER TABLE B_SEO_SEARCH_ENGINE DROP CONSTRAINT DF_B_SEO_SEARCH_ENGINE_ACTIVE
GO
ALTER TABLE B_SEO_SEARCH_ENGINE DROP CONSTRAINT DF_B_SEO_SEARCH_ENGINE_SORT
GO
DROP TABLE B_SEO_SEARCH_ENGINE
GO



ALTER TABLE B_SEO_SITEMAP DROP CONSTRAINT PK_B_SEO_SITEMAP
GO
ALTER TABLE B_SEO_SITEMAP DROP CONSTRAINT DF_B_SEO_SITEMAP_TIMESTAMP_X
GO
ALTER TABLE B_SEO_SITEMAP DROP CONSTRAINT DF_B_SEO_SITEMAP_ACTIVE
GO
DROP TABLE B_SEO_SITEMAP
GO


ALTER TABLE B_SEO_SITEMAP_RUNTIME DROP CONSTRAINT PK_B_SEO_SITEMAP_RUNTIME
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME DROP CONSTRAINT DF_B_SEO_SITEMAP_RUNTIME_PROCESSED
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME DROP CONSTRAINT DF_B_SEO_SITEMAP_RUNTIME_ITEM_TYPE
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME DROP CONSTRAINT DF_BB_SEO_SITEMAP_RUNTIME_ACTIVE
GO
ALTER TABLE B_SEO_SITEMAP_RUNTIME DROP CONSTRAINT DF_BB_SEO_SITEMAP_RUNTIME_ACTIVE_ELEMENT
GO

DROP TABLE B_SEO_SITEMAP_RUNTIME
GO

ALTER TABLE B_SEO_SITEMAP_IBLOCK DROP CONSTRAINT PK_B_SEO_SITEMAP_IBLOCK
GO
DROP TABLE B_SEO_SITEMAP_IBLOCK
GO

ALTER TABLE B_SEO_SITEMAP_ENTITY DROP CONSTRAINT PK_B_SEO_SITEMAP_ENTITY
GO
DROP TABLE B_SEO_SITEMAP_ENTITY
GO

ALTER TABLE B_SEO_ADV_CAMPAIGN DROP CONSTRAINT PK_B_SEO_ADV_CAMPAIGN
GO
ALTER TABLE B_SEO_ADV_CAMPAIGN DROP CONSTRAINT DF_B_SEO_ADV_CAMPAIGN_ACTIVE
GO
DROP TABLE B_SEO_ADV_CAMPAIGN
GO

ALTER TABLE B_SEO_ADV_GROUP DROP CONSTRAINT PK_B_SEO_ADV_GROUP
GO
ALTER TABLE B_SEO_ADV_GROUP DROP CONSTRAINT DF_B_SEO_ADV_GROUP_ACTIVE
GO
DROP TABLE B_SEO_ADV_GROUP
GO

ALTER TABLE B_SEO_ADV_BANNER DROP CONSTRAINT PK_B_SEO_ADV_BANNER
GO
ALTER TABLE B_SEO_ADV_BANNER DROP CONSTRAINT DF_B_SEO_ADV_BANNER_ACTIVE
GO
ALTER TABLE B_SEO_ADV_BANNER DROP CONSTRAINT DF_B_SEO_ADV_BANNER_AUTO_QUANTITY_OFF
GO
ALTER TABLE B_SEO_ADV_BANNER DROP CONSTRAINT DF_B_SEO_ADV_BANNER_AUTO_QUANTITY_ON
GO
DROP TABLE B_SEO_ADV_BANNER
GO



ALTER TABLE B_SEO_ADV_REGION DROP CONSTRAINT PK_B_SEO_ADV_REGION
GO
ALTER TABLE B_SEO_ADV_REGION DROP CONSTRAINT DF_B_SEO_ADV_REGION_ACTIVE
GO
DROP TABLE B_SEO_ADV_REGION
GO


ALTER TABLE B_SEO_ADV_LINK DROP CONSTRAINT PK_B_SEO_ADV_LINK
GO
DROP TABLE B_SEO_ADV_LINK
GO



ALTER TABLE B_SEO_ADV_ORDER DROP CONSTRAINT PK_B_SEO_ADV_ORDER
GO
ALTER TABLE B_SEO_ADV_ORDER DROP CONSTRAINT DF_B_SEO_ADV_ORDER_PROCESSED
GO
DROP TABLE B_SEO_ADV_ORDER
GO


ALTER TABLE B_SEO_ADV_LOG DROP CONSTRAINT PK_B_SEO_ADV_LOG
GO
DROP TABLE B_SEO_ADV_LOG
GO

ALTER TABLE B_SEO_ADV_AUTOLOG DROP CONSTRAINT PK_B_SEO_ADV_AUTOLOG
GO
DROP TABLE B_SEO_ADV_AUTOLOG
GO



ALTER TABLE B_SEO_YANDEX_DIRECT_STAT DROP CONSTRAINT PK_B_SEO_YANDEX_DIRECT_STAT
GO
DROP TABLE B_SEO_YANDEX_DIRECT_STAT
GO

