DROP TABLE B_VOXIMPLANT_STATISTIC CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_PHONE CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_CALL CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_SIP CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_CONFIG CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_QUEUE CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_BLACKLIST CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_ROLE CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_ROLE_PERMISSION CASCADE CONSTRAINTS
/
DROP TABLE B_VOXIMPLANT_ROLE_ACCESS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_VOXIMPLANT_STATISTIC
/
DROP SEQUENCE SQ_B_VOXIMPLANT_PHONE
/
DROP SEQUENCE SQ_B_VOXIMPLANT_CALL
/
DROP SEQUENCE SQ_B_VOXIMPLANT_SIP
/
DROP SEQUENCE SQ_B_VOXIMPLANT_CONFIG
/
DROP SEQUENCE SQ_B_VOXIMPLANT_QUEUE
/
DROP SEQUENCE SQ_B_VOXIMPLANT_ROLE
/
DROP SEQUENCE SQ_B_VOXIMPLANT_ROLE_PERM
/
DROP SEQUENCE SQ_B_VOXIMPLANT_ROLE_ACC
/