DROP TABLE B_CATALOG_IBLOCK
GO
DROP TABLE B_CATALOG_PRICE
GO
DROP TABLE B_CATALOG_PRODUCT
GO
DROP TABLE B_CATALOG_EXTRA
GO
DROP TABLE B_CATALOG_GROUP_LANG
GO
DROP TABLE B_CATALOG_GROUP
GO
DROP TABLE B_CATALOG_GROUP2GROUP
GO
DROP TABLE B_CATALOG_LOAD
GO
DROP TABLE B_CATALOG_EXPORT
GO
DROP TABLE B_CATALOG_PRODUCT2GROUP
GO
DROP TABLE B_CATALOG_DISCOUNT
GO
DROP TABLE B_CATALOG_DISCOUNT_COND
GO
DROP TABLE B_CATALOG_DISCOUNT_MODULE
GO
DROP TABLE B_CATALOG_DISCOUNT2PRODUCT
GO
DROP TABLE B_CATALOG_DISCOUNT2GROUP
GO
DROP TABLE B_CATALOG_DISCOUNT2CAT
GO
DROP TABLE B_CATALOG_DISCOUNT2SECTION
GO
DROP TABLE B_CATALOG_DISCOUNT2IBLOCK
GO
DROP TABLE B_CATALOG_DISCOUNT_COUPON
GO
DROP TABLE B_CATALOG_VAT
GO
DROP TABLE B_CATALOG_DISC_SAVE_RANGE
GO
DROP TABLE B_CATALOG_DISC_SAVE_GROUP
GO
DROP TABLE B_CATALOG_DISC_SAVE_USER
GO
DROP TABLE B_CATALOG_STORE
GO
DROP TABLE B_CATALOG_STORE_PRODUCT
GO
DROP TABLE B_CATALOG_STORE_BARCODE
GO
DROP TABLE B_CATALOG_CONTRACTOR
GO
DROP TABLE B_CATALOG_STORE_DOCS
GO
DROP TABLE B_CATALOG_DOCS_ELEMENT
GO
DROP TABLE B_CATALOG_DOCS_BARCODE
GO
DROP TABLE B_CATALOG_MEASURE
GO
DROP TABLE B_CATALOG_MEASURE_RATIO
GO
DROP TABLE B_CATALOG_PRODUCT_SETS
GO
DROP TABLE B_CATALOG_VIEWED_PRODUCT
GO
DROP TABLE B_CATALOG_SUBSCRIBE
GO
DROP TABLE B_CATALOG_SUBSCRIBE_ACCESS
GO
DROP TABLE B_CATALOG_ROUNDING
GO