DROP TABLE B_SEC_FILTER_MASK
GO
DROP TABLE B_SEC_IPRULE_INCL_IP
GO
DROP TABLE B_SEC_IPRULE_EXCL_IP
GO
DROP TABLE B_SEC_IPRULE_INCL_MASK
GO
DROP TABLE B_SEC_IPRULE_EXCL_MASK
GO
DROP TABLE B_SEC_IPRULE
GO
DROP TABLE B_SEC_SESSION
GO
DROP TABLE B_SEC_USER
GO
DROP TABLE B_SEC_REDIRECT_URL
GO
DROP TABLE B_SEC_WHITE_LIST
GO
DROP TABLE B_SEC_VIRUS
GO
DROP TABLE B_SEC_FRAME_MASK
GO
DROP TABLE b_security_sitecheck
GO
DROP TABLE B_SEC_RECOVERY_CODES
GO