DROP TABLE B_PERF_TEST CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_TEST
/
DROP TABLE B_PERF_ERROR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_ERROR
/
DROP TABLE B_PERF_CACHE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_CACHE
/
DROP TABLE B_PERF_SQL_BACKTRACE CASCADE CONSTRAINTS
/
DROP TABLE B_PERF_SQL CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_SQL
/
DROP TABLE B_PERF_COMPONENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_COMPONENT
/
DROP TABLE B_PERF_HIT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_HIT
/
DROP TABLE B_PERF_CLUSTER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_CLUSTER
/
DROP TABLE B_PERF_HISTORY CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_PERF_HISTORY
/
