DROP TABLE B_WORKFLOW_FILE 
GO
DROP TABLE B_WORKFLOW_LOG
GO 
DROP TABLE B_WORKFLOW_MOVE 
GO
DROP TABLE B_WORKFLOW_PREVIEW 
GO
DROP TABLE B_WORKFLOW_STATUS2GROUP 
GO
DROP TABLE B_WORKFLOW_DOCUMENT 
GO
DROP TABLE B_WORKFLOW_STATUS 
GO
