DROP TABLE B_CATALOG_IBLOCK CASCADE CONSTRAINTS
/

DROP TABLE B_CATALOG_PRICE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_PRICE
/

DROP TABLE B_CATALOG_PRODUCT CASCADE CONSTRAINTS
/

DROP TABLE B_CATALOG_EXTRA CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_EXTRA
/

DROP TABLE B_CATALOG_GROUP_LANG CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_GROUP_LANG
/

DROP TABLE B_CATALOG_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_GROUP
/

DROP TABLE B_CATALOG_GROUP2GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_GROUP2GROUP
/

DROP TABLE B_CATALOG_LOAD CASCADE CONSTRAINTS
/

DROP TABLE B_CATALOG_EXPORT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_EXPORT
/

DROP TABLE B_CATALOG_PRODUCT2GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_PRODUCT2GROUP
/

DROP TABLE B_CATALOG_DISCOUNT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT
/

DROP TABLE B_CATALOG_DISCOUNT_COND CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT_COND
/

DROP TABLE B_CATALOG_DISCOUNT_MODULE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT_MODULE
/

DROP TABLE B_CATALOG_DISCOUNT2PRODUCT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT2PRODUCT
/

DROP TABLE B_CATALOG_DISCOUNT2GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT2GROUP
/

DROP TABLE B_CATALOG_DISCOUNT2CAT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT2CAT
/

DROP TABLE B_CATALOG_DISCOUNT2SECTION CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT2SECTION
/

DROP TABLE B_CATALOG_DISCOUNT2IBLOCK CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT2IBLOCK
/

DROP TABLE B_CATALOG_DISCOUNT_COUPON CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISCOUNT_COUPON
/

DROP TABLE B_CATALOG_VAT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_VAT
/

DROP TABLE B_CATALOG_DISC_SAVE_RANGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISC_SAVE_RANGE
/

DROP TABLE B_CATALOG_DISC_SAVE_GROUP CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISC_SAVE_GROUP
/

DROP TABLE B_CATALOG_DISC_SAVE_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DISC_SAVE_USER
/

DROP TABLE B_CATALOG_STORE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_STORE
/

DROP TABLE B_CATALOG_STORE_PRODUCT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_STORE_PRODUCT
/

DROP TABLE B_CATALOG_STORE_BARCODE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_STORE_BARCODE
/

DROP TABLE B_CATALOG_CONTRACTOR CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_CONTRACTOR
/

DROP TABLE B_CATALOG_STORE_DOCS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_STORE_DOCS
/

DROP TABLE B_CATALOG_DOCS_ELEMENT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DOCS_ELEMENT
/

DROP TABLE B_CATALOG_DOCS_BARCODE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_DOCS_BARCODE
/

DROP TABLE B_CATALOG_MEASURE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_MEASURE
/

DROP TABLE B_CATALOG_MEASURE_RATIO CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_MEASURE_RATIO
/

DROP TABLE B_CATALOG_PRODUCT_SETS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_PRODUCT_SETS
/

DROP TABLE B_CATALOG_VIEWED_PRODUCT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_VIEWED_PRODUCT
/

DROP TABLE B_CATALOG_SUBSCRIBE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_SUBSCRIBE
/

DROP TABLE B_CATALOG_SUBSCRIBE_ACCESS CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_SUBSCRIBE_ACCESS
/

DROP TABLE B_CATALOG_ROUNDING CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_CATALOG_ROUNDING
/