CREATE TABLE B_B24CONNECTOR_BUTTONS
(
  ID  NUMBER(18) NOT NULL,
  APP_ID  NUMBER(18) NOT NULL,
  ADD_DATE DATE NOT NULL,
  ADD_BY NUMBER(18) NOT NULL,
  NAME VARCHAR2(255 CHAR) NULL,
  SCRIPT CLOB NULL,
  PRIMARY KEY (ID)
)
/