CREATE TABLE B_MOBILEAPP_APP
(
  CODE           VARCHAR(50) NOT NULL,
  SHORT_NAME     VARCHAR(50) NOT NULL,
  NAME           VARCHAR(50) NOT NULL,
  DESCRIPTION    TEXT        NOT NULL,
  FILES          TEXT        NOT NULL,
  LAUNCH_ICONS   TEXT        NOT NULL,
  LAUNCH_SCREENS TEXT        NOT NULL,
  FOLDER         VARCHAR(50) NOT NULL,
  DATE_CREATE    DATETIME    NOT NULL,
  PRIMARY KEY (CODE)
)
GO
CREATE TABLE B_MOBILEAPP_CONFIG (
  APP_CODE    VARCHAR(150) NOT NULL,
  PLATFORM    VARCHAR(150) NOT NULL,
  PARAMS      TEXT         NOT NULL,
  DATE_CREATE DATETIME     NOT NULL,
  PRIMARY KEY (APP_CODE, PLATFORM)
)
