DROP TABLE B_TICKET CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_DICTIONARY CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_DICTIONARY_2_SITE CASCADE CONSTRAINTS 
/
DROP TABLE B_TICKET_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_MESSAGE_2_FILE CASCADE CONSTRAINTS 
/
DROP TABLE B_TICKET_ONLINE CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_SHEDULE CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_2_SITE CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_2_CATEGORY CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_2_CRITICALITY CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_2_MARK CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SLA_2_USER_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_UGROUPS CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_USER_UGROUP CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SUPERCOUPONS CASCADE CONSTRAINTS
/
DROP TABLE B_TICKET_SUPERCOUPONS_LOG CASCADE CONSTRAINTS
/

DROP SEQUENCE SQ_B_TICKET 
/
DROP SEQUENCE SQ_B_TICKET_DICTIONARY 
/
DROP SEQUENCE SQ_B_TICKET_MESSAGE 
/
DROP SEQUENCE SQ_B_TICKET_MESSAGE_2_FILE 
/
DROP SEQUENCE SQ_B_TICKET_ONLINE 
/
DROP SEQUENCE SQ_B_TICKET_SLA
/
DROP SEQUENCE SQ_B_TICKET_SLA_SHEDULE
/
DROP SEQUENCE SQ_B_TICKET_UGROUPS
/
DROP SEQUENCE SQ_B_TICKET_SUPERCOUPONS
/

DROP TABLE b_ticket_timetable
/
DROP TABLE b_ticket_holidays
/
DROP TABLE b_ticket_sla_2_holidays
/
DROP TABLE b_ticket_search
/
DROP TABLE b_ticket_timetable_cache
/

DROP SEQUENCE SQ_b_ticket_timetable 
/
DROP SEQUENCE SQ_b_ticket_holidays 
/
DROP SEQUENCE SQ_b_ticket_timetable_cache 
/