DROP TABLE B_ADV_BANNER
GO
DROP TABLE B_ADV_BANNER_2_COUNTRY
GO
DROP TABLE B_ADV_BANNER_2_DAY
GO
DROP TABLE B_ADV_BANNER_2_SITE
GO
DROP TABLE B_ADV_BANNER_2_PAGE
GO
DROP TABLE B_ADV_BANNER_2_STAT_ADV
GO
DROP TABLE B_ADV_BANNER_2_WEEKDAY
GO
DROP TABLE B_ADV_CONTRACT
GO
DROP TABLE B_ADV_CONTRACT_2_SITE
GO
DROP TABLE B_ADV_CONTRACT_2_PAGE
GO
DROP TABLE B_ADV_CONTRACT_2_TYPE
GO
DROP TABLE B_ADV_CONTRACT_2_USER
GO
DROP TABLE B_ADV_CONTRACT_2_WEEKDAY
GO
DROP TABLE B_ADV_TYPE
GO
DROP TABLE B_ADV_BANNER_2_GROUP
GO
