DROP TABLE B_ADV_BANNER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_ADV_BANNER
/
DROP TABLE B_ADV_BANNER_2_COUNTRY CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_SITE CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_DAY CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_STAT_ADV CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_WEEKDAY CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_PAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_ADV_BANNER_2_PAGE
/
DROP TABLE B_ADV_CONTRACT CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_ADV_CONTRACT
/
DROP TABLE B_ADV_CONTRACT_2_SITE CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_CONTRACT_2_PAGE CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_ADV_CONTRACT_2_PAGE
/
DROP TABLE B_ADV_CONTRACT_2_TYPE CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_CONTRACT_2_USER CASCADE CONSTRAINTS
/
DROP SEQUENCE SQ_B_ADV_CONTRACT_2_USER
/
DROP TABLE B_ADV_CONTRACT_2_WEEKDAY CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_TYPE CASCADE CONSTRAINTS
/
DROP TABLE B_ADV_BANNER_2_GROUP CASCADE CONSTRAINTS
/
