DROP PROCEDURE DELFILE
/
DROP TABLE B_LANG CASCADE CONSTRAINTS
/
DROP TABLE B_LANGUAGE CASCADE CONSTRAINTS
/
DROP TABLE B_LANG_DOMAIN CASCADE CONSTRAINTS
/
DROP TABLE B_SITE_TEMPLATE CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_TYPE  CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_MESSAGE CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_MESSAGE_SITE CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT CASCADE CONSTRAINTS
/
DROP TABLE B_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_USER CASCADE CONSTRAINTS
/
DROP TABLE B_USER_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE CASCADE CONSTRAINTS
/
DROP TABLE B_AGENT CASCADE CONSTRAINTS
/
DROP TABLE B_OPTION CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE_TO_MODULE CASCADE CONSTRAINTS
/
DROP TABLE B_FILE CASCADE CONSTRAINTS
/
DROP TABLE B_FILE_ACTION CASCADE CONSTRAINTS
/
DROP TABLE B_MODULE_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_FAVORITE CASCADE CONSTRAINTS
/
DROP TABLE B_USER_STORED_AUTH CASCADE CONSTRAINTS
/
DROP TABLE B_USER_OPTION CASCADE CONSTRAINTS
/
DROP TABLE B_CAPTCHA CASCADE CONSTRAINTS
/
DROP TABLE B_USER_FIELD_ENUM CASCADE CONSTRAINTS
/
DROP TABLE B_USER_FIELD_LANG CASCADE CONSTRAINTS
/
DROP TABLE B_USER_FIELD CASCADE CONSTRAINTS
/
DROP TABLE B_GROUP_TASK CASCADE CONSTRAINTS
/
DROP TABLE B_TASK_OPERATION CASCADE CONSTRAINTS
/
DROP TABLE B_OPERATION CASCADE CONSTRAINTS
/
DROP TABLE B_GROUP_SUBORDINATE CASCADE CONSTRAINTS
/
DROP TABLE B_TASK CASCADE CONSTRAINTS
/
DROP TABLE B_EVENT_LOG CASCADE CONSTRAINTS
/
DROP TABLE B_CACHE_TAG CASCADE CONSTRAINTS
/
DROP TABLE B_USER_HIT_AUTH CASCADE CONSTRAINTS
/
DROP TABLE b_undo CASCADE CONSTRAINTS
/
DROP TABLE B_RATING CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_COMPONENT CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_COMPONENT_RESULTS CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_RESULTS CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_VOTE CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_VOTING CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_USER CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_WEIGHT CASCADE CONSTRAINTS
/
DROP TABLE B_RATING_VOTE_GROUP CASCADE CONSTRAINTS
/
DROP TABLE B_CHECKLIST
/
DROP TABLE B_SHORT_URI
/
DROP TABLE B_USER_COUNTER
/
DROP TABLE B_USER_ACCESS
/
DROP TABLE B_USER_ACCESS_CHECK
/
DROP TABLE B_HOT_KEYS
/
DROP TABLE B_HOT_KEYS_CODE
/
DROP TABLE B_ADMIN_NOTIFY
/
DROP TABLE B_FILTERS
/
DROP SEQUENCE SQ_B_EVENT_LOG
/
DROP SEQUENCE SQ_B_EVENT_TYPE
/
DROP SEQUENCE SQ_B_SITE_TEMPLATE
/
DROP SEQUENCE SQ_B_FILE_ACTION
/
DROP SEQUENCE SQ_B_FILE
/
DROP SEQUENCE SQ_B_AGENT
/
DROP SEQUENCE SQ_B_EVENT_MESSAGE
/
DROP SEQUENCE SQ_B_EVENT
/
DROP SEQUENCE SQ_B_USER
/
DROP SEQUENCE SQ_B_GROUP
/
DROP SEQUENCE SQ_B_MODULE_GROUP
/
DROP SEQUENCE SQ_B_FAVORITE
/
DROP SEQUENCE SQ_B_MODULE_TO_MODULE
/
DROP SEQUENCE SQ_B_USER_STORED_AUTH
/
DROP SEQUENCE SQ_B_USER_OPTION
/
DROP SEQUENCE SQ_B_USER_FIELD
/
DROP SEQUENCE SQ_B_USER_FIELD_LANG
/
DROP SEQUENCE SQ_B_USER_FIELD_ENUM
/
DROP SEQUENCE SQ_B_TASK
/
DROP SEQUENCE SQ_B_OPERATION
/
DROP SEQUENCE SQ_B_USER_HIT_AUTH
/
DROP SEQUENCE SQ_B_RATING
/
DROP SEQUENCE SQ_B_RATING_COMPONENT
/
DROP SEQUENCE SQ_B_RATING_COMPONENT_RESULTS
/
DROP SEQUENCE SQ_B_RATING_RESULTS
/
DROP SEQUENCE SQ_B_RATING_VOTE
/
DROP SEQUENCE SQ_B_RATING_VOTING
/
DROP SEQUENCE SQ_B_RATING_RULE
/
DROP SEQUENCE SQ_B_RATING_RULE_VETTING
/
DROP SEQUENCE SQ_B_RATING_USER
/
DROP SEQUENCE SQ_B_RATING_WEIGHT
/
DROP SEQUENCE SQ_B_RATING_VOTE_GROUP
/
DROP SEQUENCE SQ_B_CHECKLIST
/
DROP SEQUENCE SQ_B_SHORT_URI
/
DROP SEQUENCE SQ_B_HOT_KEYS
/
DROP SEQUENCE SQ_B_HOT_KEYS_CODE
/
DROP SEQUENCE SQ_B_ADMIN_NOTIFY
/
DROP SEQUENCE SQ_B_FILTERS
/
