DROP TABLE B_MAIL_MAILBOX
GO
DROP TABLE B_MAIL_FILTER
GO
DROP TABLE B_MAIL_FILTER_COND
GO
DROP TABLE B_MAIL_MESSAGE
GO
DROP TABLE B_MAIL_MESSAGE_UID
GO
DROP TABLE B_MAIL_MSG_ATTACHMENT 
GO
DROP TABLE B_MAIL_SPAM_WEIGHT
GO
DROP TABLE B_MAIL_LOG 
GO
DROP TABLE B_MAIL_MAILSERVICES
GO
DROP TABLE B_MAIL_USER_RELATIONS
GO
DROP TABLE B_MAIL_BLACKLIST
GO
DROP TABLE B_MAIL_DOMAIN_EMAIL
GO