DROP TABLE B_BP_WORKFLOW_TEMPLATE CASCADE CONSTRAINTS
/
DROP TABLE B_BP_WORKFLOW_STATE CASCADE CONSTRAINTS
/
DROP TABLE B_BP_WORKFLOW_PERMISSIONS CASCADE CONSTRAINTS
/
DROP TABLE B_BP_WORKFLOW_INSTANCE CASCADE CONSTRAINTS
/
DROP TABLE B_BP_TRACKING CASCADE CONSTRAINTS
/
DROP TABLE B_BP_TASK CASCADE CONSTRAINTS
/
DROP TABLE B_BP_TASK_USER CASCADE CONSTRAINTS
/
DROP TABLE B_BP_HISTORY CASCADE CONSTRAINTS
/
DROP TABLE B_BP_WORKFLOW_STATE_IDENTIFY CASCADE CONSTRAINTS
/
DROP TABLE B_BP_REST_ACTIVITY CASCADE CONSTRAINTS
/
DROP TABLE B_BP_SCHEDULER_EVENT CASCADE CONSTRAINTS
/

DROP SEQUENCE SQ_B_BP_WORKFLOW_TEMPLATE
/
DROP SEQUENCE SQ_B_BP_WORKFLOW_PERMISSIONS
/
DROP SEQUENCE SQ_B_BP_TRACKING
/
DROP SEQUENCE SQ_B_BP_TASK
/
DROP SEQUENCE SQ_B_BP_TASK_USER
/
DROP SEQUENCE SQ_B_BP_HISTORY
/
DROP SEQUENCE S_B_BP_WORKFLOW_STATE_IDENTIFY
/
DROP SEQUENCE SQ_B_BP_REST_ACTIVITY
/
DROP SEQUENCE SQ_B_BP_SCHEDULER_EVENT
/